createOrReplace

	model Model
		culture: en-US
		defaultPowerBIDataSourceVersion: powerBI_V3
		discourageImplicitMeasures
		sourceQueryCulture: en-AT
		dataAccessOptions
			legacyRedirects
			returnErrorValuesAsNull

		table dTickers
			lineageTag: 73ed73ea-8ba7-42bf-b21b-01591a862ac9

			column Ticker
				dataType: string
				lineageTag: f7ba25c9-dc46-4567-bb33-d9e55012bef6
				summarizeBy: none
				sourceColumn: Ticker

				annotation SummarizationSetBy = Automatic

			column currency
				dataType: string
				lineageTag: d6081160-0051-4aa9-b092-4c2a933d387d
				summarizeBy: none
				sourceColumn: currency

				annotation SummarizationSetBy = Automatic

			column symbol
				dataType: string
				lineageTag: 41c8dd64-881d-473b-b9cd-cdd6a5bad12c
				summarizeBy: none
				sourceColumn: symbol

				annotation SummarizationSetBy = Automatic

			column exchangeName
				dataType: string
				lineageTag: 304d55de-5710-45cd-8b92-ceb31dac4e04
				summarizeBy: none
				sourceColumn: exchangeName

				annotation SummarizationSetBy = Automatic

			column fullExchangeName
				dataType: string
				lineageTag: c66a336f-7c0d-4d3c-863c-22eb94031bd6
				summarizeBy: none
				sourceColumn: fullExchangeName

				annotation SummarizationSetBy = Automatic

			column instrumentType
				dataType: string
				lineageTag: f7681fa8-b19d-40f6-aae8-559e6e4b34d5
				summarizeBy: none
				sourceColumn: instrumentType

				annotation SummarizationSetBy = Automatic

			column firstTradeDate
				dataType: string
				lineageTag: 330f953b-80c0-4988-aeb2-53c67ebd33d8
				summarizeBy: none
				sourceColumn: firstTradeDate

				annotation SummarizationSetBy = Automatic

			column regularMarketTime
				dataType: string
				lineageTag: cbff8497-37b9-4235-9726-bdf3b8b950b2
				summarizeBy: none
				sourceColumn: regularMarketTime

				annotation SummarizationSetBy = Automatic

			column hasPrePostMarketData
				dataType: string
				lineageTag: 08dd9925-68a8-4b16-9cab-525c69d8747c
				summarizeBy: none
				sourceColumn: hasPrePostMarketData

				annotation SummarizationSetBy = Automatic

			column gmtoffset
				dataType: string
				lineageTag: ce1f217b-dea3-4975-8b15-27ec0ded96a6
				summarizeBy: none
				sourceColumn: gmtoffset

				annotation SummarizationSetBy = Automatic

			column timezone
				dataType: string
				lineageTag: 7efd2810-6b90-4471-8414-49715d3ad1ed
				summarizeBy: none
				sourceColumn: timezone

				annotation SummarizationSetBy = Automatic

			column exchangeTimezoneName
				dataType: string
				lineageTag: 8c1bbe50-5e00-4e1f-9a6d-7f26a6089c3e
				summarizeBy: none
				sourceColumn: exchangeTimezoneName

				annotation SummarizationSetBy = Automatic

			column regularMarketPrice
				dataType: string
				lineageTag: c2f9425b-3a98-4d65-8146-3829c474a083
				summarizeBy: none
				sourceColumn: regularMarketPrice

				annotation SummarizationSetBy = Automatic

			column fiftyTwoWeekHigh
				dataType: string
				lineageTag: aa0b9cd5-0db4-41cf-a5aa-ae703d11d96e
				summarizeBy: none
				sourceColumn: fiftyTwoWeekHigh

				annotation SummarizationSetBy = Automatic

			column fiftyTwoWeekLow
				dataType: string
				lineageTag: c720008c-590b-419d-87df-1e59f72a5ebe
				summarizeBy: none
				sourceColumn: fiftyTwoWeekLow

				annotation SummarizationSetBy = Automatic

			column regularMarketDayHigh
				dataType: string
				lineageTag: 2719cee2-daf6-4fd1-8a3b-f4bb5eacf9d0
				summarizeBy: none
				sourceColumn: regularMarketDayHigh

				annotation SummarizationSetBy = Automatic

			column regularMarketDayLow
				dataType: string
				lineageTag: 845ffcb8-3529-4c55-a202-b34d83282e7e
				summarizeBy: none
				sourceColumn: regularMarketDayLow

				annotation SummarizationSetBy = Automatic

			column regularMarketVolume
				dataType: string
				lineageTag: 2614be25-cb5a-4603-8d61-93884dbb59b3
				summarizeBy: none
				sourceColumn: regularMarketVolume

				annotation SummarizationSetBy = Automatic

			column longName
				dataType: string
				lineageTag: 8638557c-35ef-445e-96a8-16d1a48f5ece
				summarizeBy: none
				sourceColumn: longName

				annotation SummarizationSetBy = Automatic

			column shortName
				dataType: string
				lineageTag: e46ce882-9eff-481f-a0d8-9adc80aea8ee
				summarizeBy: none
				sourceColumn: shortName

				annotation SummarizationSetBy = Automatic

			column chartPreviousClose
				dataType: string
				lineageTag: bec902e2-5b53-40a4-9407-9bd8ba2db6da
				summarizeBy: none
				sourceColumn: chartPreviousClose

				annotation SummarizationSetBy = Automatic

			column priceHint
				dataType: string
				lineageTag: 6e87c386-4857-4d73-8ec3-f594fd695a85
				summarizeBy: none
				sourceColumn: priceHint

				annotation SummarizationSetBy = Automatic

			column currentTradingPeriod
				dataType: string
				lineageTag: 80b8bea8-ff7a-4e81-b962-8403de821f39
				summarizeBy: none
				sourceColumn: currentTradingPeriod

				annotation SummarizationSetBy = Automatic

			column dataGranularity
				dataType: string
				lineageTag: 528a9081-f01e-4591-86dc-6c9c7b9d89d9
				summarizeBy: none
				sourceColumn: dataGranularity

				annotation SummarizationSetBy = Automatic

			column range
				dataType: string
				lineageTag: 3711745e-bd33-4272-91d2-3a79a6c82b32
				summarizeBy: none
				sourceColumn: range

				annotation SummarizationSetBy = Automatic

			column validRanges
				dataType: string
				lineageTag: d3e06571-6e5b-4740-a0ea-a8de6edaedf0
				summarizeBy: none
				sourceColumn: validRanges

				annotation SummarizationSetBy = Automatic

			column Name = dTickers[shortName] & " ("&dTickers[Ticker]&")"
				lineageTag: 588c8a0d-98ed-4ea6-8c53-6be2f0ff921c
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			partition dTickers = m
				mode: import
				queryGroup: 'Dimension Tables'
				source = ```
						let
						    //Import the CSV of Tickers
						
						    Source = Csv.Document(
						        File.Contents(PathtoTickersCSV),
						        [Delimiter=",", Columns=1, QuoteStyle=QuoteStyle.None]
						    ),
						    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
						    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Ticker", type text}}),
						
						    //Add a column that calls the API and returns raw JSON for each Ticker
						    WithAPICall = Table.AddColumn(
						        #"Changed Type",
						        "APICall",
						        each 
						            Web.Contents(
						                "https://query1.finance.yahoo.com",
						                [
						                    RelativePath = "v8/finance/chart/" & [Ticker],
						                    Query = [
						                        interval = Interval,
						                        range   = Range
						                    ]
						                ]
						            )
						    ),
						    //Parse the JSON into a usable record
						    WithParsedJSON = Table.AddColumn(
						        WithAPICall,
						        "ParsedJSON",
						        each Json.Document([APICall])
						    ),
						    #"Removed Columns" = Table.RemoveColumns(WithParsedJSON,{"APICall"}),
						    #"Expanded ParsedJSON" = Table.ExpandRecordColumn(#"Removed Columns", "ParsedJSON", {"chart"}, {"chart"}),
						    #"Expanded chart" = Table.ExpandRecordColumn(#"Expanded ParsedJSON", "chart", {"result"}, {"result"}),
						    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Expanded chart", {"result"}),
						    #"Expanded result" = Table.ExpandListColumn(#"Removed Errors", "result"),
						    #"Expanded result1" = Table.ExpandRecordColumn(#"Expanded result", "result", {"meta"}, {"meta"}),
						    #"Expanded meta" = Table.ExpandRecordColumn(#"Expanded result1", "meta", {"currency", "symbol", "exchangeName", "fullExchangeName", "instrumentType", "firstTradeDate", "regularMarketTime", "hasPrePostMarketData", "gmtoffset", "timezone", "exchangeTimezoneName", "regularMarketPrice", "fiftyTwoWeekHigh", "fiftyTwoWeekLow", "regularMarketDayHigh", "regularMarketDayLow", "regularMarketVolume", "longName", "shortName", "chartPreviousClose", "priceHint", "currentTradingPeriod", "dataGranularity", "range", "validRanges"}, {"currency", "symbol", "exchangeName", "fullExchangeName", "instrumentType", "firstTradeDate", "regularMarketTime", "hasPrePostMarketData", "gmtoffset", "timezone", "exchangeTimezoneName", "regularMarketPrice", "fiftyTwoWeekHigh", "fiftyTwoWeekLow", "regularMarketDayHigh", "regularMarketDayLow", "regularMarketVolume", "longName", "shortName", "chartPreviousClose", "priceHint", "currentTradingPeriod", "dataGranularity", "range", "validRanges"})
						in
						    #"Expanded meta"
						```

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table factIndicators
			lineageTag: 6a92cfc3-5781-478a-95e0-564e70cc9adc

			column Ticker
				dataType: string
				lineageTag: 289c4a15-50c1-489b-aba6-25684d4d3dda
				summarizeBy: none
				sourceColumn: Ticker

				annotation SummarizationSetBy = Automatic

			column 'DateTime (UTC)'
				dataType: dateTime
				formatString: General Date
				lineageTag: ed9123f9-f9f7-4ada-b8e8-bc528bfb26d1
				summarizeBy: none
				sourceColumn: DateTime (UTC)

				annotation SummarizationSetBy = Automatic

			column Open
				dataType: double
				lineageTag: e035daef-bfcc-43c1-8b4d-3d8342a45513
				summarizeBy: sum
				sourceColumn: Open

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column High
				dataType: double
				lineageTag: ea0633de-3d6c-4191-9b16-5cfd5e64819a
				summarizeBy: sum
				sourceColumn: High

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column Low
				dataType: double
				lineageTag: 8a588002-83a4-41ab-af61-b529ab4d9bef
				summarizeBy: sum
				sourceColumn: Low

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column Close
				dataType: double
				lineageTag: dfbdd23f-d91d-444d-a8af-53e5fe575d1c
				summarizeBy: sum
				sourceColumn: Close

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column Volume
				dataType: int64
				formatString: 0
				lineageTag: 26be6a75-b4e0-436b-bd28-ad8f803f41bc
				summarizeBy: sum
				sourceColumn: Volume

				annotation SummarizationSetBy = Automatic

			column Date
				dataType: dateTime
				formatString: Long Date
				lineageTag: ac4a4f63-97b3-469a-bcb3-bd2539f47ce0
				summarizeBy: none
				sourceColumn: Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column Time
				dataType: dateTime
				formatString: Long Time
				lineageTag: b2f45e0c-d0ea-4fbc-b080-f734f929b9a8
				summarizeBy: none
				sourceColumn: Time

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Time

			partition factIndicators = m
				mode: import
				queryGroup: 'Fact Tables'
				source = ```
						let
						    //Import the CSV of Tickers
						
						    Source = Csv.Document(
						        File.Contents(PathtoTickersCSV),
						        [Delimiter=",", Columns=1, QuoteStyle=QuoteStyle.None]
						    ),
						    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
						    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Ticker", type text}}),
						
						    //Add a column that calls the API and returns raw JSON for each Ticker
						    WithAPICall = Table.AddColumn(
						        #"Changed Type",
						        "APICall",
						        each 
						            Web.Contents(
						                "https://query1.finance.yahoo.com",
						                [
						                    RelativePath = "v8/finance/chart/" & [Ticker],
						                    Query = [
						                        interval = Interval,
						                        range   = Range
						                    ]
						                ]
						            )
						    ),
						    //Parse the JSON into a usable record
						    WithParsedJSON = Table.AddColumn(
						        WithAPICall,
						        "ParsedJSON",
						        each Json.Document([APICall])
						    ),
						    // This step extracts timestamps, open, high, low, close, volume arrays and transforms them into a proper table (one row per historical record).
						    WithDataTable = Table.AddColumn(
						        WithParsedJSON,
						        "HistoricData",
						        each
						            let
						                rawJson                = [ParsedJSON],
						                chartRecord            = rawJson[chart],
						                resultsList            = chartRecord[result],
						                firstResult            = resultsList{0},
						                timestamps            = firstResult[timestamp],
						                indicatorsRecord       = firstResult[indicators],
						                quoteList              = indicatorsRecord[quote],
						                firstQuote             = quoteList{0},
						                opens                  = firstQuote[open],
						                highs                  = firstQuote[high],
						                lows                   = firstQuote[low],
						                closes                = firstQuote[close],
						                volumes                = firstQuote[volume],
						
						                // Build a list of records from the arrays
						                combinedRecords = List.Transform(
						                    {0..(List.Count(timestamps) - 1)},
						                    (i) => [
						                        timestamp = timestamps{i},
						                        open      = opens{i},
						                        high      = highs{i},
						                        low       = lows{i},
						                        close     = closes{i},
						                        volume    = volumes{i}
						                    ]
						                ),
						
						                // Convert the list of records into a table
						                dataTable = Table.FromRecords(combinedRecords)
						            in
						                dataTable
						    ),
						    ExpandedData = Table.ExpandTableColumn(
						        WithDataTable,
						        "HistoricData",
						        {"timestamp","open","high","low","close","volume"},
						        {"timestamp","open","high","low","close","volume"}
						    ),
						
						    // Unix timestamps to human-readable DateTime
						    WithDateTime = Table.TransformColumns(
						        ExpandedData,
						        {
						            { 
						                "timestamp", 
						                each #datetime(1970, 1, 1, 0, 0, 0) + #duration(0,0,0,_), 
						                type datetime 
						            }
						        }
						    ),
						
						
						    RenamedColumns = Table.RenameColumns(
						        WithDateTime,
						        {
						            {"timestamp", "DateTime (UTC)"},
						            {"open", "Open"},
						            {"high", "High"},
						            {"low", "Low"},
						            {"close", "Close"},
						            {"volume", "Volume"}
						        }
						    ),
						    #"Removed Columns" = Table.RemoveColumns(RenamedColumns,{"APICall", "ParsedJSON"}),
						    #"Inserted Date" = Table.AddColumn(#"Removed Columns", "Date", each DateTime.Date([#"DateTime (UTC)"]), type date),
						    #"Inserted Time" = Table.AddColumn(#"Inserted Date", "Time", each DateTime.Time([#"DateTime (UTC)"]), type time),
						    #"Changed Type for numbers" = Table.TransformColumnTypes(#"Inserted Time",{{"Close", type number}, {"Low", type number}, {"High", type number}, {"Open", type number}, {"Volume", Int64.Type}})
						in
						    #"Changed Type for numbers"
						```

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table _Measures
			lineageTag: e18fec4d-e6d1-459d-a072-a082425d8b7c

			/// The “Close Price” measure computes the average of the 'Close' column
			/// for the current filter context (e.g., date, ticker).
			/// "Close" represents the final trading price of the stock on a given day (or interval).
			/// Using AVERAGE() here makes sense if you have multiple intraday rows that you want
			/// to aggregate into a single representative price for each context.
			/// If each date/ticker only has a single Close value, AVERAGE() = that value
			measure ClosePrice = ```
					
					/* The “Close Price” measure computes the average of the 'Close' column
					 for the current filter context (e.g., date, ticker).
					 "Close" represents the final trading price of the stock on a given day (or interval).
					 Using AVERAGE() here makes sense if you have multiple intraday rows that you want
					 to aggregate into a single representative price for each context.
					 If each date/ticker only has a single Close value, AVERAGE() = that value*/
					AVERAGE('factIndicators'[Close])
					
					
					```
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Basic metrics
				lineageTag: 2585ac4d-3f94-4b6b-946d-6ee0b9c3e4b4

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			/// The “Total Volume” measure sums the 'Volume' column
			/// for the current filter context (e.g., date range, ticker).
			/// "Volume" is the total number of shares (or contracts) traded during a specific period.
			measure TotalVolume = ```
					
					/* The “Total Volume” measure sums the 'Volume' column
					 for the current filter context (e.g., date range, ticker).
					 "Volume" is the total number of shares (or contracts) traded during a specific period.
					*/
					SUM('factIndicators'[Volume])
					
					```
				formatString: 0
				displayFolder: Basic metrics
				lineageTag: 112b4a18-1ca2-4978-b3b8-5fef901514d3

			/// The “SMA (50-Day)” measure calculates a 50-day Simple Moving Average of the closing price.
			/// A simple moving average smooths out short-term fluctuations in the price over a specific period.
			/// This measure looks back 50 calendar days from the current context date (inclusive).
			measure SimpleMovingAverage = ```
					
					/* The Simple Moving Average of the closing price.
					 A simple moving average smooths out short-term fluctuations in the price over a specific period.
					 This measure looks back 50 calendar days from the current context date (inclusive).
					*/
					CALCULATE(
					    [ClosePrice],
					    DATESINPERIOD(
					        'Calendar'[Date],
					        MAX('Calendar'[Date]),
					        -SELECTEDVALUE('DaysMovingAverageParameter'[Days], 15),
					        DAY
					    )
					)
					
					```
				displayFolder: Moving averages
				lineageTag: 3f584946-c9b2-4ea7-92f4-d0853a8338da

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure OpenPrice =
					
					/* The “Open Price” measure computes the average of the 'Open' column
					   for the current filter context (e.g., date, ticker).
					   "Open" represents the initial trading price of the stock on a given day (or interval).
					   Using AVERAGE() here makes sense if you have multiple intraday rows that you want
					   to aggregate into a single representative price for each context.
					   If each date/ticker only has a single Open value, AVERAGE() = that value */
					AVERAGE('factIndicators'[Open])
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Basic metrics
				lineageTag: 445ae17e-0451-45a2-a6f7-151d44f95d0e

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			measure HighPrice = ```
					
					/* The “High Price” measure computes the average of the 'High' column
					   for the current filter context (e.g., date, ticker).
					   "High" represents the highest trading price of the stock on a given day (or interval).
					   Using AVERAGE() here is consistent with the approach for other price measures 
					   if you have multiple intraday rows that you want
					   to aggregate into a single representative price for each context.
					   If each date/ticker only has a single High value, AVERAGE() = that value */
					AVERAGE('factIndicators'[High])
					```
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Basic metrics
				lineageTag: 376dd24b-77d0-4c19-9742-fd9d45b92ade

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			measure LowPrice = ```
					
					/* The “Low Price” measure computes the average of the 'Low' column
					   for the current filter context (e.g., date, ticker).
					   "Low" represents the lowest trading price of the stock on a given day (or interval).
					   Using AVERAGE() here is consistent with the approach for other price measures 
					   if you have multiple intraday rows that you want
					   to aggregate into a single representative price for each context.
					   If each date/ticker only has a single Low value, AVERAGE() = that value */
					AVERAGE('factIndicators'[Low])
					
					```
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Basic metrics
				lineageTag: 5e2e5401-f84f-4522-94ae-74bea53ac0e6

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			measure 'Candlestick Title' = ```
					
					VAR SelectedTicker = SELECTEDVALUE('factIndicators'[Ticker])
					VAR SelectedCompany = SELECTEDVALUE(dTickers[shortName],"Multiple Stocks")
					RETURN "Daily Stock Price Fluctuations – " & SelectedCompany & " ("&SelectedTicker&")"
					
					```
				displayFolder: Titles
				lineageTag: 59f39dc5-b794-4614-8276-1262fc44c82e

			measure PriceChange = ```
					[ClosePrice] - [OpenPrice]
					
					```
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				displayFolder: Basic metrics
				lineageTag: da70fdc8-4ffe-46c0-b803-47482fa57513

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			measure PriceChangeRelative = ```
					DIVIDE([ClosePrice] - [OpenPrice],[OpenPrice])
					
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				displayFolder: Basic metrics
				lineageTag: 5473e64f-549e-4655-9299-d1b94235d2f9

			/// "Quarterly P/E Ratio" compares a stock's recent price/earnings multiple.
			measure Pe = ```
					
					// "Quarterly P/E Ratio (Current)" compares a stock's recent price/earnings multiple.
					VAR CurrentDate = MAX('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyPeRatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = CurrentDate)
					)
					
					```
				displayFolder: Metrics 3M
				lineageTag: 09f5ece3-493a-4133-aa90-239ff648bef9

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// The “Quarterly Forward P/E Ratio” uses projected (forecasted) quarterly earnings instead of historical data,
			/// offering a forward-looking valuation multiple.
			measure ForwardPe =
					
					/* The “Quarterly Forward P/E Ratio” uses projected (forecasted) quarterly earnings instead of historical data,
					   offering a forward-looking valuation multiple.*/
					VAR CurrentDate = MAX('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyForwardPeRatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = CurrentDate)
					)
				displayFolder: Metrics 3M
				lineageTag: 8235a8f6-0f40-4d99-8063-0a353b750d83

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "PEG" (Price/Earnings to Growth) compares the P/E ratio to the company's quarterly earnings growth, aiming to provide a more growth-adjusted valuation view.
			measure Peg =
					
					// "PEG" (Price/Earnings to Growth) compares the P/E ratio to the company's quarterly earnings growth, aiming to provide a more growth-adjusted valuation view.
					VAR CurrentDate = MAX('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyPegRatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = CurrentDate)
					)
				displayFolder: Metrics 3M
				lineageTag: 4f295397-261f-4125-9ab2-3c562e4ac424

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// Price-to-Sales" compares the stock's price to its quarterly revenue (on a per-share basis).
			measure Ps =
					
					// Price-to-Sales" compares the stock's price to its quarterly revenue (on a per-share basis).
					VAR CurrentDate = MAX('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyPsRatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = CurrentDate)
					)
				displayFolder: Metrics 3M
				lineageTag: ba123e6e-8d61-46cc-badb-09b0fa0f17fe

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Market Cap" represents the total value of all a company's shares.
			measure MarketCap =
					
					// "Market Cap" represents the total value of all a company's shares.
					VAR CurrentDate = MAX('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyMarketCap]),
					    KEEPFILTERS('dFundamentals3M'[Date] = CurrentDate)
					)
				formatString: \$#,0;(\$#,0);\$#,0
				displayFolder: Metrics 3M
				lineageTag: 55c09ac8-9c6a-45ff-ad13-89c0159a2748

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			measure EnterprisesValueRevenue =
					
					// "EV/Revenue" divides Enterprise Value by quarterly revenue, indicating how much investors pay per dollar of sales.
					VAR CurrentDate = MAX('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyEnterprisesValueRevenueRatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = CurrentDate)
					)
				displayFolder: Metrics 3M
				lineageTag: 5c55c4da-b879-4e62-8a86-249583730b7a

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// This ratio divides Enterprise Value by quarterly EBITDA, a common measure of operating performance,to show how the market values the company relative to its earnings potential.
			measure EnterprisesValueEBITDA =
					
					//This ratio divides Enterprise Value by quarterly EBITDA, a common measure of operating performance,to show how the market values the company relative to its earnings potential.
					VAR CurrentDate = MAX('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyEnterprisesValueEBITDARatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = CurrentDate)
					)
				displayFolder: Metrics 3M
				lineageTag: 63e3f31d-8199-4c43-8040-6a125f080d16

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// Enterprise Value (EV) is a measure of a company's total value, incorporating market cap plus debt, minus cash.
			measure EnterpriseValue = ```
					
					// Enterprise Value (EV) is a measure of a company's total value, incorporating market cap plus debt, minus cash.
					VAR CurrentDate = MAX('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyEnterpriseValue]),
					    KEEPFILTERS('dFundamentals3M'[Date] = CurrentDate)
					)
					
					```
				formatString: \$#,0;(\$#,0);\$#,0
				displayFolder: Metrics 3M
				lineageTag: 9b076b16-97df-469c-ae94-e865ed61115a

			/// "Price-to-Book" compares the stock's price per share to its book value per share, indicating how the market values the company's assets relative to its share price.
			measure Pb =
					
					// "Price-to-Book" compares the stock's price per share to its book value per share, indicating how the market values the company's assets relative to its share price.
					VAR CurrentDate = MAX('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyPbRatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = CurrentDate)
					)
				displayFolder: Metrics 3M
				lineageTag: 8b283b58-df61-4e7a-85c2-c95fb29b5e63

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Quarterly P/E Ratio" compares a stock's recent price/earnings multiple.
			measure PePrevious =
					
					VAR PreviousDate = Min('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyPeRatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = PreviousDate)
					)
				displayFolder: Metrics 3M
				lineageTag: 016fee6a-adb6-4b7b-b5e4-dae0c2e1304e

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// Price-to-Sales" compares the stock's price to its quarterly revenue (on a per-share basis).
			measure PsPrevious = ```
					
					VAR PreviousDate = MIN('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyPsRatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = PreviousDate)
					)
					
					```
				displayFolder: Metrics 3M
				lineageTag: 293ed32c-3931-4a77-b648-6516c01b208a

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "PEG" (Price/Earnings to Growth) compares the P/E ratio to the company's quarterly earnings growth, aiming to provide a more growth-adjusted valuation view.
			measure PegPrevious =
					
					VAR PreviousDate = MIN('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyPegRatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = PreviousDate)
					)
				displayFolder: Metrics 3M
				lineageTag: c813a347-0904-4cec-8296-b353ae49454b

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Price-to-Book" compares the stock's price per share to its book value per share, indicating how the market values the company's assets relative to its share price.
			measure PbPrevious = ```
					
					VAR PreviousDate = MIN('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyPbRatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = PreviousDate)
					)
					
					```
				displayFolder: Metrics 3M
				lineageTag: cca3f2eb-7ce2-4467-a939-93dde6b9b7ff

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Market Cap" represents the total value of all a company's shares.
			measure MarketCapPrevious = ```
					
					VAR PreviousDate = MIN('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyMarketCap]),
					    KEEPFILTERS('dFundamentals3M'[Date] = PreviousDate)
					)
					
					```
				displayFolder: Metrics 3M
				lineageTag: 259d3400-42ca-461f-ac5f-9f8189ed273d

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// The “Quarterly Forward P/E Ratio” uses projected (forecasted) quarterly earnings instead of historical data,
			/// offering a forward-looking valuation multiple.
			measure ForwardPePrevious = ```
					
					VAR PreviousDate = MIN('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyForwardPeRatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = PreviousDate)
					)
					
					```
				displayFolder: Metrics 3M
				lineageTag: 11eb319c-0731-467f-a0fc-8898d3e25c59

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// Enterprise Value (EV) is a measure of a company's total value, incorporating market cap plus debt, minus cash.
			measure EnterpriseValuePrevious = ```
					
					VAR PreviousDate = MIN('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyEnterpriseValue]),
					    KEEPFILTERS('dFundamentals3M'[Date] = PreviousDate)
					)
					
					```
				displayFolder: Metrics 3M
				lineageTag: 6d3ee300-0992-44bb-9b01-46ce905a20c9

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// This ratio divides Enterprise Value by quarterly EBITDA, a common measure of operating performance,to show how the market values the company relative to its earnings potential.
			measure EnterprisesValueEBITDAPrevious = ```
					
					VAR PreviousDate = MIN('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyEnterprisesValueEBITDARatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = PreviousDate)
					)
					
					```
				displayFolder: Metrics 3M
				lineageTag: 1af396db-6519-48f1-8301-d6bb8c4171e0

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure PeChange = [Pe]-[PePrevious]
				displayFolder: Metrics 3M
				lineageTag: f0daffb3-deed-4e84-9d7e-ca7e3c87a6d3

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure PsChange = [Ps] - [PsPrevious]
				displayFolder: Metrics 3M
				lineageTag: f16c6949-2eec-4ea0-a6ab-84f8eb6aea22

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure PegChange = [Peg] -[PegPrevious]
				displayFolder: Metrics 3M
				lineageTag: b9ace433-5527-4c47-8ba7-f331243c126a

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure PbChange = [Pb] - [PbPrevious]
				displayFolder: Metrics 3M
				lineageTag: 048d079f-7120-4245-b4b7-2b141bac9f11

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure EnterprisesValueEBITDAChange = [EnterprisesValueEBITDA]-[EnterprisesValueEBITDAPrevious]
				displayFolder: Metrics 3M
				lineageTag: 9508c2a2-16a2-417a-bdfc-67c8a8dce804

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure EnterprisesValueRevenuePrevious =
					
					VAR PreviousDate = MIN('dFundamentals3M'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentals3M'[quarterlyEnterprisesValueRevenueRatio]),
					    KEEPFILTERS('dFundamentals3M'[Date] = PreviousDate)
					)
				displayFolder: Metrics 3M
				lineageTag: d9a3f7a2-43f4-4407-a536-4590b33a2dfe

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure EnterprisesValueRevenueChange = [EnterprisesValueRevenue]-[EnterprisesValueRevenuePrevious]
				displayFolder: Metrics 3M
				lineageTag: 64af1225-c8f8-4e3d-a392-975aa25e14d4

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure ForwardPeChange = [ForwardPe]-[ForwardPePrevious]
				displayFolder: Metrics 3M
				lineageTag: a8d959b7-4ce4-42ec-b810-bb55da070574

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure EnterpriseValueChange = [EnterpriseValue]-[EnterpriseValuePrevious]
				displayFolder: Metrics 3M
				lineageTag: d69a38b1-76b5-4801-a761-00f27454ccf7

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure MarketCapChange = [MarketCap]-[MarketCapPrevious]
				displayFolder: Metrics 3M
				lineageTag: ef0b0dba-e0ec-4d7f-ba4c-fabbb8f8e294

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing P/E Ratio (Current)" measures a company's price-to-earnings multiple
			/// based on the last 12 months.
			measure trailingPeRatio = ```
					
					// "Trailing P/E Ratio (Current)" measures a company's price-to-earnings multiple 
					// based on the last 12 months. It uses the max date in dFundamentalsTTM.
					VAR CurrentDate = MAX('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingPeRatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = CurrentDate)
					)
					
					```
				displayFolder: Metrics TTM
				lineageTag: e1f18d61-0924-49c6-aca9-a2939f0744a8

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing P/E Ratio (Current)" measures a company's price-to-earnings multiple
			/// based on the last 12 months.
			measure trailingPeRatioPrevious = ```
					
					// "Trailing P/E Ratio (Previous)" calculates the TTM P/E at the min date 
					// (assuming 2 distinct dates). Useful for comparing change over time.
					VAR PreviousDate = MIN('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingPeRatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = PreviousDate)
					)
					```
				displayFolder: Metrics TTM
				lineageTag: 55af9b3e-a3ba-4e9c-af1a-d63c7d224932

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing P/E Ratio (Current)" measures a company's price-to-earnings multiple
			/// based on the last 12 months.
			measure trailingPeRatioChange =
					
					// "Trailing P/E Ratio (Change)" is the absolute difference between Current and Previous.
					[trailingPeRatio] - [trailingPeRatioPrevious]
				displayFolder: Metrics TTM
				lineageTag: c5d80b7c-b825-43ca-9fdb-7ef6f6ba9752

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing Forward P/E Ratio (Current)" uses projected earnings over a trailing period, capturing future expectations
			/// 
			measure trailingForwardPeRatio = ```
					
					// "Trailing Forward P/E Ratio (Current)" uses projected earnings over a trailing period, 
					// capturing future expectations. Applies the max date filter.
					VAR CurrentDate = MAX('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingForwardPeRatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = CurrentDate)
					)
					```
				displayFolder: Metrics TTM
				lineageTag: b6547bb1-0ba0-4c09-85a2-0e6110689451

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing Forward P/E Ratio (Current)" uses projected earnings over a trailing period, capturing future expectations
			/// 
			measure trailingForwardPeRatioPrevious =
					
					// "Trailing Forward P/E Ratio (Previous)" at the min date, for comparison against the current forward P/E.
					VAR PreviousDate = MIN('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingForwardPeRatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = PreviousDate)
					)
				displayFolder: Metrics TTM
				lineageTag: 9c04d926-aa62-4425-92f0-b13d4354948b

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing Forward P/E Ratio (Current)" uses projected earnings over a trailing period, capturing future expectations
			/// 
			measure trailingForwardPeRatioChange = ```
					
					// "Trailing Forward P/E Ratio (Change)" is the absolute difference 
					// between the current and previous trailing forward P/E.
					[trailingForwardPeRatio] - [trailingForwardPeRatioPrevious]
					```
				displayFolder: Metrics TTM
				lineageTag: 84b0c536-0ed7-4301-8952-1af4b3d054dd

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing Market Cap (Current)" gives the total valuation of a company’s shares over the TTM period
			measure trailingMarketCap =
					
					// "Trailing Market Cap (Current)" gives the total valuation of a company’s shares over the TTM period, using the max date in dFundamentalsTTM.
					VAR CurrentDate = MAX('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingMarketCap]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = CurrentDate)
					)
				displayFolder: Metrics TTM
				lineageTag: 6cd1ee08-b51a-434a-97be-62e0c6a2baa8

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing Market Cap (Current)" gives the total valuation of a company’s shares over the TTM period
			measure trailingMarketCapPrevious = ```
					
					// "Trailing Market Cap (Previous)" at the min date, to see how 
					// market valuation changed between two TTM snapshots.
					VAR PreviousDate = MIN('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingMarketCap]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = PreviousDate)
					)
					```
				displayFolder: Metrics TTM
				lineageTag: 07b38fc3-9b94-4654-90f1-6e13482afd37

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing Market Cap (Current)" gives the total valuation of a company’s shares over the TTM period
			measure trailingMarketCapChange = ```
					
					// "Trailing Market Cap (Change)" is the difference in market cap 
					// from the earliest to the latest TTM date.
					[trailingMarketCap] - [trailingMarketCapPrevious]
					```
				displayFolder: Metrics TTM
				lineageTag: dbaafd76-1f76-4ba5-bdec-5b15a9be4f26

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing Enterprise Value (Current)" includes market cap plus debt minus cash
			measure trailingEnterpriseValue =
					
					// "Trailing Enterprise Value (Current)" includes market cap plus debt minus cash, referencing the last TTM date for each Ticker.
					VAR CurrentDate = MAX('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingEnterpriseValue]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = CurrentDate)
					)
				formatString: #,0.00
				displayFolder: Metrics TTM
				lineageTag: ecc99ab3-0cba-45b5-bd21-2a517bed96e5

			/// "Trailing Enterprise Value (Current)" includes market cap plus debt minus cash
			measure trailingEnterpriseValuePrevious =
					
					// "Trailing Enterprise Value (Previous)" for the min date, enabling quarter-to-quarter or period-to-period comparisons within TTM data.
					VAR PreviousDate = MIN('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingEnterpriseValue]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = PreviousDate)
					)
				displayFolder: Metrics TTM
				lineageTag: f8a78f0e-0424-4284-96d2-169b87d65720

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing Enterprise Value (Current)" includes market cap plus debt minus cash
			measure trailingEnterpriseValueChange = ```
					
					// "Trailing Enterprise Value (Change)" is the absolute difference 
					// between Current and Previous TTM EV.
					[trailingEnterpriseValue] - [trailingEnterpriseValuePrevious]
					```
				displayFolder: Metrics TTM
				lineageTag: 5cc5d9c9-8f85-4cdd-a429-b3cd22093c55

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing EV/EBITDA (Current)" measures Enterprise Value over EBITDA for the trailing 12 months
			measure trailingEnterprisesValueEBITDARatio =
					
					// "Trailing EV/EBITDA (Current)" measures Enterprise Value over EBITDA for the trailing 12 months, referencing the max date in the table.
					VAR CurrentDate = MAX('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingEnterprisesValueEBITDARatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = CurrentDate)
					)
				displayFolder: Metrics TTM
				lineageTag: a9846e48-7f30-418b-b2b8-a4f886d850ae

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing EV/EBITDA (Current)" measures Enterprise Value over EBITDA for the trailing 12 months
			measure trailingEnterprisesValueEBITDARatioPrevious = ```
					
					/* "Trailing EV/EBITDA (Previous)" uses the earliest TTM date per Ticker to show 
					   how this ratio has changed. */
					VAR PreviousDate = MIN('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingEnterprisesValueEBITDARatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = PreviousDate)
					)
					```
				displayFolder: Metrics TTM
				lineageTag: 2b9bd822-6ff5-45cb-9513-e28f2f53d0de

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing EV/EBITDA (Current)" measures Enterprise Value over EBITDA for the trailing 12 months
			measure trailingEnterprisesValueEBITDARatioChange = ```
					
					/* "Trailing EV/EBITDA (Change)" is the difference between the Current 
					   and Previous TTM EV/EBITDA ratio. */
					[trailingEnterprisesValueEBITDARatio] - [trailingEnterprisesValueEBITDARatioPrevious]
					```
				displayFolder: Metrics TTM
				lineageTag: 4f52fb99-7bc1-497b-813a-8376281841fc

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing PEG Ratio (Current)" uses TTM data to compare price/earnings to growth.
			measure trailingPegRatio = ```
					
					// "Trailing PEG Ratio (Current)" uses TTM data to compare price/earnings to growth. 
					VAR CurrentDate = MAX('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingPegRatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = CurrentDate)
					)
					```
				displayFolder: Metrics TTM
				lineageTag: c07baad2-1280-4bd0-b8d6-902fb0a00b91

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing PEG Ratio (Current)" uses TTM data to compare price/earnings to growth.
			measure trailingPegRatioPrevious =
					
					// "Trailing PEG Ratio (Previous)" references the earliest TTM date for each Ticker,
					// letting you see how the growth-based valuation changed.
					VAR PreviousDate = MIN('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingPegRatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = PreviousDate)
					)
				displayFolder: Metrics TTM
				lineageTag: 95512fe3-b2ad-4b1d-ae00-474d14d364a7

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing PEG Ratio (Current)" uses TTM data to compare price/earnings to growth.
			measure trailingPegRatioChange = ```
					
					// "Trailing PEG Ratio (Change)" is the numeric difference between 
					// the current and previous TTM PEG Ratio.
					[trailingPegRatio] - [trailingPegRatioPrevious]
					```
				displayFolder: Metrics TTM
				lineageTag: 2e29b67d-94ea-4a1b-ba67-481e2910d320

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing EV/Revenue (Current)" calculates Enterprise Value Revenue for the trailing 12 months
			measure trailingEnterprisesValueRevenueRatio =
					
					// "Trailing EV/Revenue (Current)" calculates Enterprise Value Revenue for the trailing 12 months at the max date.
					VAR CurrentDate = MAX('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingEnterprisesValueRevenueRatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = CurrentDate)
					)
				displayFolder: Metrics TTM
				lineageTag: 7843c49d-3c98-4a20-bbd1-fd7310905751

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing EV/Revenue (Current)" calculates Enterprise Value Revenue for the trailing 12 months
			measure trailingEnterprisesValueRevenueRatioPrevious =
					
					// "Trailing EV/Revenue (Previous)" uses the min date to see how this valuation metric changed.
					VAR PreviousDate = MIN('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingEnterprisesValueRevenueRatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = PreviousDate)
					)
				displayFolder: Metrics TTM
				lineageTag: 478e718c-d06a-4bd5-9bcc-226988fba8b3

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing EV/Revenue (Current)" calculates Enterprise Value Revenue for the trailing 12 months
			measure trailingEnterprisesValueRevenueRatioChange = ```
					
					// "Trailing EV/Revenue (Change)" is simply the difference 
					// between the current and previous TTM ratio.
					[trailingEnterprisesValueRevenueRatio] - [trailingEnterprisesValueRevenueRatioPrevious]
					```
				displayFolder: Metrics TTM
				lineageTag: 02eeaca1-24a7-478c-872a-df1d28a44947

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing P/B Ratio (Current)" for the trailing 12 months
			measure trailingPbRatio =
					
					// "Trailing P/B Ratio (Current)" for the trailing 12 months, referencing the max date in dFundamentalsTTM.
					VAR CurrentDate = MAX('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingPbRatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = CurrentDate)
					)
				displayFolder: Metrics TTM
				lineageTag: 77bce7f8-aadc-4d66-9d4a-718a7854de99

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing P/B Ratio (Current)" for the trailing 12 months
			measure trailingPbRatioPrevious =
					
					// "Trailing P/B Ratio (Previous)" referencing the min date, letting you see if the company's price-to-book changed significantly over time.
					VAR PreviousDate = MIN('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingPbRatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = PreviousDate)
					)
				displayFolder: Metrics TTM
				lineageTag: 4a88824c-e5d1-49b9-b81b-be76123ca8b9

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing P/B Ratio (Current)" for the trailing 12 months
			measure trailingPbRatioChange = ```
					
					// "Trailing P/B Ratio (Change)" is the absolute difference 
					// from the earliest to the latest TTM date for each Ticker.
					[trailingPbRatio] - [trailingPbRatioPrevious]
					```
				displayFolder: Metrics TTM
				lineageTag: f472a77d-4167-47b7-9cb1-759197c1ce7d

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing P/S Ratio (Current)" calculates Price-to-Sales using the TTM period
			measure trailingPsRatio =
					
					// "Trailing P/S Ratio (Current)" calculates Price-to-Sales using the TTM period at the max date for each Ticker.
					VAR CurrentDate = MAX('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingPsRatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = CurrentDate)
					)
				displayFolder: Metrics TTM
				lineageTag: f5a5ef33-b7b6-4f1d-9005-cf48cfbdc8c4

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing P/S Ratio (Current)" calculates Price-to-Sales using the TTM period
			measure trailingPsRatioPrevious =
					
					// "Trailing P/S Ratio (Previous)" uses the min date to compare how the P/S changed from earliest to latest TTM date.
					VAR PreviousDate = MIN('dFundamentalsTTM'[Date])
					RETURN
					CALCULATE(
					    AVERAGE('dFundamentalsTTM'[trailingPsRatio]),
					    KEEPFILTERS('dFundamentalsTTM'[Date] = PreviousDate)
					)
				displayFolder: Metrics TTM
				lineageTag: 18878fc0-2096-4ce3-9714-9b9c40849daf

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			/// "Trailing P/S Ratio (Current)" calculates Price-to-Sales using the TTM period
			measure trailingPsRatioChange = ```
					
					// "Trailing P/S Ratio (Change)" is the difference 
					// between the current and previous TTM ratio.
					[trailingPsRatio] - [trailingPsRatioPrevious]
					```
				displayFolder: Metrics TTM
				lineageTag: 13ce38dd-ceca-48a6-b908-71436104cd95

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			partition _Measures = m
				mode: import
				source =
						let
						    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
						    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
						    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
						in
						    #"Removed Columns"

			annotation PBI_ResultType = Table

			annotation PBI_NavigationStepName = Navigation

		table Calendar
			lineageTag: f5618063-a41f-4b73-b950-101e4401f1cd

			column Date
				formatString: dd/mm/yyyy
				lineageTag: 02f98b62-cba4-4e9f-a87c-ac112eb03b5f
				summarizeBy: none
				isNameInferred
				sourceColumn: [Date]

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isDateTimeCustom":true}

			column Year
				formatString: 0
				lineageTag: 8f5566d8-29dc-4b15-8f18-e388acb90c2f
				summarizeBy: none
				isNameInferred
				sourceColumn: [Year]

				annotation SummarizationSetBy = Automatic

			column Quarter
				lineageTag: e0ef7e09-caa4-472a-8e53-82cc5ebc385f
				summarizeBy: none
				isNameInferred
				sourceColumn: [Quarter]

				annotation SummarizationSetBy = Automatic

			column MonthNumber
				formatString: 0
				lineageTag: 9425f6ea-1ab8-459e-9886-2cc86ca24b2f
				summarizeBy: none
				isNameInferred
				sourceColumn: [MonthNumber]

				annotation SummarizationSetBy = Automatic

			column MonthName
				lineageTag: d390bb77-6e31-46c1-8a09-747d014b0b58
				summarizeBy: none
				isNameInferred
				sourceColumn: [MonthName]

				annotation SummarizationSetBy = Automatic

			column YearMonth
				lineageTag: c97c3f3c-9a31-4c48-a16a-711fadd594c7
				summarizeBy: none
				isNameInferred
				sourceColumn: [YearMonth]

				annotation SummarizationSetBy = Automatic

			column DayOfWeek
				lineageTag: 6eebb1d3-7439-4267-beab-6ac9433d490c
				summarizeBy: none
				isNameInferred
				sourceColumn: [DayOfWeek]

				annotation SummarizationSetBy = Automatic

			partition Calendar = calculated
				mode: import
				source = ```
						
						ADDCOLUMNS(
						    CALENDAR(
						        MINX('factIndicators', 'factIndicators'[DateTime (UTC)]),
						        MAXX('factIndicators', 'factIndicators'[DateTime (UTC)])
						    ),
						    "Year",         YEAR([Date]),
						    "Quarter",      "Q" & FORMAT([Date], "Q"),
						    "MonthNumber",  MONTH([Date]),
						    "MonthName",    FORMAT([Date], "MMMM"),
						    "YearMonth",    FORMAT([Date], "YYYY-MM"),
						    "DayOfWeek",    FORMAT([Date], "ddd")
						)
						
						```

			annotation PBI_Id = fac9ad0580844c678460dd9b19a76888

		table DaysMovingAverageParameter
			lineageTag: 0ff9407e-80ae-452e-ad58-e9e8077a408a

			column Days
				formatString: 0
				lineageTag: 647c387c-bfd0-41b7-942f-c16b7e400864
				summarizeBy: none
				sourceColumn: [Value]

				extendedProperty ParameterMetadata =
						{
						  "version": 0
						}

				annotation SummarizationSetBy = User

			partition DaysMovingAverageParameter = calculated
				mode: import
				source = GENERATESERIES(1, 100, 1)

			annotation PBI_Id = eb54c3662d4d4c1ab3aa50a39a4dab0a

		table dFundamentalsTTM
			lineageTag: 9410422e-fd11-4484-ae26-534c52e77992

			column Date
				dataType: dateTime
				formatString: Long Date
				lineageTag: c6244c92-1dc6-4eb8-b020-6e60fc3f06e5
				summarizeBy: none
				sourceColumn: Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column periodType
				dataType: string
				lineageTag: 26d6c5b3-82e9-4766-9e80-8314001f4901
				summarizeBy: none
				sourceColumn: periodType

				annotation SummarizationSetBy = Automatic

			column Ticker
				dataType: string
				lineageTag: 2e474036-2080-4edd-aaad-c8a7fa1fe216
				summarizeBy: none
				sourceColumn: Ticker

				annotation SummarizationSetBy = Automatic

			column trailingEnterprisesValueEBITDARatio
				dataType: double
				lineageTag: 60d4561d-17a0-4aa0-b03e-67683648fdfe
				summarizeBy: sum
				sourceColumn: trailingEnterprisesValueEBITDARatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column trailingForwardPeRatio
				dataType: double
				lineageTag: 3e98d13f-f1bf-45f8-8c9b-44afcce0ab3d
				summarizeBy: sum
				sourceColumn: trailingForwardPeRatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column trailingMarketCap
				dataType: double
				lineageTag: 479ed35b-6d6f-468b-af67-9bf06837544f
				summarizeBy: sum
				sourceColumn: trailingMarketCap

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column trailingEnterpriseValue
				dataType: double
				lineageTag: 2574e424-dfb1-4ff8-9a54-1b9e10b7a761
				summarizeBy: sum
				sourceColumn: trailingEnterpriseValue

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column trailingPegRatio
				dataType: double
				lineageTag: 57ae7c81-2a02-445a-8c7f-3465a2ab3c60
				summarizeBy: sum
				sourceColumn: trailingPegRatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column trailingPeRatio
				dataType: double
				lineageTag: 6e16b356-290f-4b28-b2ae-a2d8945c046d
				summarizeBy: sum
				sourceColumn: trailingPeRatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column trailingEnterprisesValueRevenueRatio
				dataType: double
				lineageTag: befb8ef0-0266-4567-ba32-aa94b4edc978
				summarizeBy: sum
				sourceColumn: trailingEnterprisesValueRevenueRatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column trailingPbRatio
				dataType: double
				lineageTag: f58a5e5c-db80-48f3-b9a5-aff503f9d554
				summarizeBy: sum
				sourceColumn: trailingPbRatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column trailingPsRatio
				dataType: double
				lineageTag: 9c5decc5-9bf6-426f-9f18-c5dd53b5038b
				summarizeBy: sum
				sourceColumn: trailingPsRatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			partition dFundamentalsTTM = m
				mode: import
				queryGroup: 'Dimension Tables'
				source =
						let
						    Source = dFundamentals,
						    #"Filtered Rows" = Table.SelectRows(Source, each ([periodType] = "TTM")),
						    #"Pivoted Column" = Table.Pivot(#"Filtered Rows", List.Distinct(#"Filtered Rows"[metricType]), "metricType", "Raw Value", List.Sum)
						in
						    #"Pivoted Column"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table dFundamentals3M
			lineageTag: e2631038-4f81-4720-aa5f-1c6b6fd860ec

			column Date
				dataType: dateTime
				formatString: Long Date
				lineageTag: 6f678268-89a0-49d0-baa0-29f28aa9ee80
				summarizeBy: none
				sourceColumn: Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column periodType
				dataType: string
				lineageTag: 892bcd9e-d807-4ca3-953d-09faf560aadd
				summarizeBy: none
				sourceColumn: periodType

				annotation SummarizationSetBy = Automatic

			column Ticker
				dataType: string
				lineageTag: 50ebe7d9-ca58-41d8-b057-c710a2653b1a
				summarizeBy: none
				sourceColumn: Ticker

				annotation SummarizationSetBy = Automatic

			column quarterlyPeRatio
				dataType: double
				lineageTag: 5fc76250-0dea-444f-9e27-b7c380722881
				summarizeBy: sum
				sourceColumn: quarterlyPeRatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column quarterlyForwardPeRatio
				dataType: double
				lineageTag: 38999c0b-b710-47fe-9603-e38204461602
				summarizeBy: sum
				sourceColumn: quarterlyForwardPeRatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column quarterlyPegRatio
				dataType: double
				lineageTag: 63133a39-148c-41f3-a641-bb4b6f682be3
				summarizeBy: sum
				sourceColumn: quarterlyPegRatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column quarterlyPsRatio
				dataType: double
				lineageTag: 939e45ac-82ef-4301-9aeb-54c5dee26a4d
				summarizeBy: sum
				sourceColumn: quarterlyPsRatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column quarterlyMarketCap
				dataType: double
				lineageTag: bc8bb8d2-972b-4c34-88e4-4a5bc7eacbda
				summarizeBy: sum
				sourceColumn: quarterlyMarketCap

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column quarterlyEnterprisesValueRevenueRatio
				dataType: double
				lineageTag: 0aa0cd3d-a643-4a21-b9af-82a458360d80
				summarizeBy: sum
				sourceColumn: quarterlyEnterprisesValueRevenueRatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column quarterlyEnterprisesValueEBITDARatio
				dataType: double
				lineageTag: e9b8cd0d-418c-416b-9883-4641e5b2a223
				summarizeBy: sum
				sourceColumn: quarterlyEnterprisesValueEBITDARatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column quarterlyEnterpriseValue
				dataType: double
				lineageTag: 2c6a091c-9e40-4853-8cc4-13fafe57f18d
				summarizeBy: sum
				sourceColumn: quarterlyEnterpriseValue

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column quarterlyPbRatio
				dataType: double
				lineageTag: 055c318e-363b-4540-a334-33252c4c8551
				summarizeBy: sum
				sourceColumn: quarterlyPbRatio

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			partition dFundamentals3M = m
				mode: import
				queryGroup: 'Dimension Tables'
				source =
						let
						    Source = dFundamentals,
						    #"Filtered Rows" = Table.SelectRows(Source, each ([periodType] = "3M")),
						    #"Pivoted Column" = Table.Pivot(#"Filtered Rows", List.Distinct(#"Filtered Rows"[metricType]), "metricType", "Raw Value", List.Sum)
						in
						    #"Pivoted Column"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		relationship AutoDetected_bbb74ba3-fe6d-421b-be56-5dc1fc4519e3
			fromColumn: factIndicators.Ticker
			toColumn: dTickers.Ticker

		relationship e2f9efff-f8ba-dbfe-047e-73bc8c637f59
			fromColumn: factIndicators.Date
			toColumn: Calendar.Date

		relationship AutoDetected_27cbec65-ebae-499f-8750-43e20008e8f5
			fromColumn: dFundamentalsTTM.Ticker
			toColumn: dTickers.Ticker

		relationship AutoDetected_02d4a809-3790-490b-b5cf-66d235b9f762
			fromColumn: dFundamentals3M.Ticker
			toColumn: dTickers.Ticker

		cultureInfo en-US

			linguisticMetadata = {"Version":"3.5.0","Language":"en-US","Entities":{"d_ticker":{"Definition":{"Binding":{"ConceptualEntity":"dTickers"}},"State":"Generated","Terms":[{"d ticker":{"State":"Generated"}},{"dTickers":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"d_ticker.ticker":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"Ticker"}},"State":"Generated","Terms":[{"ticker":{"State":"Generated"}}]},"d_ticker.currency":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"currency"}},"State":"Generated","Terms":[{"currency":{"State":"Generated"}},{"money":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"coinage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"cash":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"prevalence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"frequency":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"popularity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"vogue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"circulation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"commonness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"acceptance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"d_ticker.symbol":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"symbol"}},"State":"Generated","Terms":[{"symbol":{"State":"Generated"}},{"representation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"icon":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"pictogram":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"sign":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"character":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"figure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"mark":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"emblem":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"indication":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"logo":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"d_ticker.exchange_name":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"exchangeName"}},"State":"Generated","Terms":[{"exchange name":{"State":"Generated"}},{"exchangeName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"exchange":{"State":"Generated","Weight":0.97}},{"exchange nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"exchange title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"exchange label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"exchange tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"conversation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"argument":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"discussion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"altercation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"talk":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"chat":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"d_ticker.full_exchange_name":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"fullExchangeName"}},"State":"Generated","Terms":[{"full exchange name":{"State":"Generated"}},{"fullExchangeName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"exchange":{"State":"Generated","Weight":0.97}},{"full exchange nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"full exchange title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"full exchange label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"full exchange tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"complete exchange name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"entire exchange name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"whole exchange name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"conversation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"argument":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"discussion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"d_ticker.instrument_type":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"instrumentType"}},"State":"Generated","Terms":[{"instrument type":{"State":"Generated"}},{"instrumentType":{"Type":"Noun","State":"Generated","Weight":0.99}},{"type":{"State":"Generated","Weight":0.97}},{"instrument category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"instrument genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"instrument manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"instrument variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"instrument brand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"instrument class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"d_ticker.first_trade_date":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"firstTradeDate"}},"State":"Generated","Terms":[{"first trade date":{"State":"Generated"}},{"firstTradeDate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"trade date":{"State":"Generated","Weight":0.97}},{"first trade moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"trade moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"first trade period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"trade period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"d_ticker.regular_market_time":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"regularMarketTime"}},"State":"Generated","Terms":[{"regular market time":{"State":"Generated"}},{"regularMarketTime":{"Type":"Noun","State":"Generated","Weight":0.99}},{"market time":{"State":"Generated","Weight":0.97}},{"regular market duration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"regular market interval":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"regular market moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"market duration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"market interval":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"market moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"regular market period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"regular market timetable":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"market period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"market timetable":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"d_ticker.has_pre_post_market_data":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"hasPrePostMarketData"}},"State":"Generated","Terms":[{"has pre post market data":{"State":"Generated"}},{"hasPrePostMarketData":{"Type":"Noun","State":"Generated","Weight":0.99}},{"has pre post market information":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.78}},{"has pre post market fact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.78}},{"has pre post market info":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.78}},{"has pre post market statistic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.78}},{"has pre post market document":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.757}},{"has pre post market figure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.757}},{"has pre post market record":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.757}},{"has pre column market data":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"has pre post marketplace data":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"has pre post souk data":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}}]},"d_ticker.gmtoffset":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"gmtoffset"}},"State":"Generated","Terms":[{"gmtoffset":{"State":"Generated"}}]},"d_ticker.timezone":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"timezone"}},"State":"Generated","Terms":[{"timezone":{"State":"Generated"}}]},"d_ticker.exchange_timezone_name":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"exchangeTimezoneName"}},"State":"Generated","Terms":[{"exchange timezone name":{"State":"Generated"}},{"exchangeTimezoneName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"exchange timezone nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"exchange timezone title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"exchange timezone label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"exchange timezone tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}}]},"d_ticker.regular_market_price":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"regularMarketPrice"}},"State":"Generated","Terms":[{"regular market price":{"State":"Generated"}},{"regularMarketPrice":{"Type":"Noun","State":"Generated","Weight":0.99}},{"price":{"State":"Generated","Weight":0.97}},{"market price":{"State":"Generated","Weight":0.97}},{"regular market value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"regular market worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"regular market fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"regular market charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"regular market amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"regular market bill":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"regular market rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"regular market expense":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"regular market cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"regular market outlay":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}}]},"d_ticker.fifty_two_week_high":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"fiftyTwoWeekHigh"}},"State":"Generated","Terms":[{"fifty two week high":{"State":"Generated"}},{"fiftyTwoWeekHigh":{"Type":"Noun","State":"Generated","Weight":0.99}},{"week high":{"State":"Generated","Weight":0.97}},{"two week high":{"State":"Generated","Weight":0.97}}]},"d_ticker.fifty_two_week_low":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"fiftyTwoWeekLow"}},"State":"Generated","Terms":[{"fifty two week low":{"State":"Generated"}},{"fiftyTwoWeekLow":{"Type":"Noun","State":"Generated","Weight":0.99}},{"week low":{"State":"Generated","Weight":0.97}},{"two week low":{"State":"Generated","Weight":0.97}}]},"d_ticker.regular_market_day_high":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"regularMarketDayHigh"}},"State":"Generated","Terms":[{"regular market day high":{"State":"Generated"}},{"regularMarketDayHigh":{"Type":"Noun","State":"Generated","Weight":0.99}},{"day high":{"State":"Generated","Weight":0.97}},{"market day high":{"State":"Generated","Weight":0.97}}]},"d_ticker.regular_market_day_low":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"regularMarketDayLow"}},"State":"Generated","Terms":[{"regular market day low":{"State":"Generated"}},{"regularMarketDayLow":{"Type":"Noun","State":"Generated","Weight":0.99}},{"day low":{"State":"Generated","Weight":0.97}},{"market day low":{"State":"Generated","Weight":0.97}}]},"d_ticker.regular_market_volume":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"regularMarketVolume"}},"State":"Generated","Terms":[{"regular market volume":{"State":"Generated"}},{"regularMarketVolume":{"Type":"Noun","State":"Generated","Weight":0.99}},{"market volume":{"State":"Generated","Weight":0.97}},{"regular market capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"regular market size":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"regular market bulk":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"market capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"market size":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"market bulk":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"regular market tome":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"market tome":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"regular market book":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"regular market work":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}}]},"d_ticker.long_name":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"longName"}},"State":"Generated","Terms":[{"long name":{"State":"Generated"}},{"longName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"long nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"long title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"long label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"long tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"d_ticker.short_name":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"shortName"}},"State":"Generated","Terms":[{"short name":{"State":"Generated"}},{"shortName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"short":{"State":"Generated","Weight":0.97}},{"short nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"short title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"short label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"short tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"small":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"little":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"petite":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"squat":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"diminutive":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"brief":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"d_ticker.chart_previous_close":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"chartPreviousClose"}},"State":"Generated","Terms":[{"chart previous close":{"State":"Generated"}},{"chartPreviousClose":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"d_ticker.price_hint":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"priceHint"}},"State":"Generated","Terms":[{"price hint":{"State":"Generated"}},{"priceHint":{"Type":"Noun","State":"Generated","Weight":0.99}},{"hint":{"State":"Generated","Weight":0.97}},{"price suggestion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"price intimation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"price indication":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"price tipoff":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"price insinuation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"price allusion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"suggestion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"intimation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"indication":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"tipoff":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"d_ticker.current_trading_period":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"currentTradingPeriod"}},"State":"Generated","Terms":[{"current trading period":{"State":"Generated"}},{"currentTradingPeriod":{"Type":"Noun","State":"Generated","Weight":0.99}},{"period":{"State":"Generated","Weight":0.97}},{"trading period":{"State":"Generated","Weight":0.97}},{"latest trading period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"contemporary trading period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"present trading period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"present day trading period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.484}},{"current trading era":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"current trading epoch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"trading era":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"trading epoch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"current trading age":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"current trading stage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}}]},"d_ticker.data_granularity":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"dataGranularity"}},"State":"Generated","Terms":[{"data granularity":{"State":"Generated"}},{"dataGranularity":{"Type":"Noun","State":"Generated","Weight":0.99}},{"granularity":{"State":"Generated","Weight":0.97}},{"information granularity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"fact granularity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"info granularity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"statistic granularity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"document granularity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"figure granularity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"record granularity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"d_ticker.range":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"range"}},"State":"Generated","Terms":[{"range":{"State":"Generated"}},{"variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"series":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"assortment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"collection":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"gamut":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"selection":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"choice":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"array":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"scope":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"d_ticker.valid_range":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"validRanges"}},"State":"Generated","Terms":[{"valid range":{"State":"Generated"}},{"validRanges":{"Type":"Noun","State":"Generated","Weight":0.99}},{"valid variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"valid series":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"valid assortment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"valid collection":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"valid gamut":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"valid selection":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"valid choice":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"valid array":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"valid kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"valid sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"fact_indicator":{"Definition":{"Binding":{"ConceptualEntity":"factIndicators"}},"State":"Generated","Terms":[{"fact indicator":{"State":"Generated"}},{"factIndicators":{"Type":"Noun","State":"Generated","Weight":0.99}},{"indicator":{"State":"Generated","Weight":0.97}},{"fact pointer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pointer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"fact needle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"fact gage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"fact gauge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"fact dial":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"fact meter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"fact display":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"needle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"gage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"fact_indicator.ticker":{"Definition":{"Binding":{"ConceptualEntity":"factIndicators","ConceptualProperty":"Ticker"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"ticker":{"State":"Generated"}}]},"fact_indicator.DateTime_UTC":{"Definition":{"Binding":{"ConceptualEntity":"factIndicators","ConceptualProperty":"DateTime (UTC)"}},"State":"Generated","Terms":[{"DateTime (UTC)":{"State":"Generated"}},{"DateTime":{"State":"Generated","Weight":0.75}}],"SemanticType":"Time"},"fact_indicator.open":{"Definition":{"Binding":{"ConceptualEntity":"factIndicators","ConceptualProperty":"Open"}},"State":"Generated","Terms":[{"open":{"State":"Generated"}},{"sweeping":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"fact_indicator.high":{"Definition":{"Binding":{"ConceptualEntity":"factIndicators","ConceptualProperty":"High"}},"State":"Generated","Terms":[{"high":{"State":"Generated"}},{"great":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"extreme":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"fact_indicator.low":{"Definition":{"Binding":{"ConceptualEntity":"factIndicators","ConceptualProperty":"Low"}},"State":"Generated","Terms":[{"low":{"State":"Generated"}},{"little":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"squat":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"low-slung":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"small":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"soothing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"quiet":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"gentle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"faint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"fact_indicator.close":{"Definition":{"Binding":{"ConceptualEntity":"factIndicators","ConceptualProperty":"Close"}},"State":"Generated","Terms":[{"close":{"State":"Generated"}},{"local":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"neighboring":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"intimate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"familiar":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"dear":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"loving":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"friendly":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"warm":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"fact_indicator.volume":{"Definition":{"Binding":{"ConceptualEntity":"factIndicators","ConceptualProperty":"Volume"}},"State":"Generated","Terms":[{"volume":{"State":"Generated"}},{"capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"size":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"bulk":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"tome":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"book":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"work":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"fact_indicator.date":{"Definition":{"Binding":{"ConceptualEntity":"factIndicators","ConceptualProperty":"Date"}},"State":"Generated","Terms":[{"date":{"State":"Generated"}},{"moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}],"SemanticType":"Time"},"fact_indicator.time":{"Definition":{"Binding":{"ConceptualEntity":"factIndicators","ConceptualProperty":"Time"}},"State":"Generated","Terms":[{"time":{"State":"Generated"}},{"duration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"interval":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"timetable":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}],"SemanticType":"Time"},"entity__measure":{"Definition":{"Binding":{"ConceptualEntity":"_Measures"}},"State":"Generated","Terms":[{"_measure":{"State":"Generated"}},{"_ degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"_ quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"_ quota":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"_ extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"_ amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"_ portion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"_ ration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"_ size":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"entity__measure.close_price":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"ClosePrice"}},"State":"Generated","Terms":[{"close price":{"State":"Generated"}},{"ClosePrice":{"Type":"Noun","State":"Generated","Weight":0.99}},{"price":{"State":"Generated","Weight":0.97}},{"close value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"close worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"close fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"close charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"close amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"close bill":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"close rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"close expense":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"close cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"close outlay":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"Close":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.total_volume":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"TotalVolume"}},"State":"Generated","Terms":[{"total volume":{"State":"Generated"}},{"TotalVolume":{"Type":"Noun","State":"Generated","Weight":0.99}},{"aggregate volume":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"overall volume":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"total capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total size":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total bulk":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"total tome":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"total book":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"total work":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"total edition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.451}}]},"entity__measure.simple_moving_average":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"SimpleMovingAverage"}},"State":"Generated","Terms":[{"SimpleMovingAverage":{"LastModified":"2025-02-27T07:36:23.434Z"}},{"simple moving average":{"State":"Generated"}},{"moving average":{"State":"Generated","Weight":0.97}},{"simple moving mode":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"simple moving norm":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"moving mode":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"moving norm":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"simple moving mean":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"simple moving median":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"moving mean":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"moving median":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"moving averagesSimpleMovingAverage":{"State":"Deleted","LastModified":"2025-02-27T07:36:23.435Z"}}]},"entity__measure.open_price":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"OpenPrice"}},"State":"Generated","Terms":[{"open price":{"State":"Generated"}},{"OpenPrice":{"Type":"Noun","State":"Generated","Weight":0.99}},{"price":{"State":"Generated","Weight":0.97}},{"open value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"open worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"open fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"open charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"open amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"open bill":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"open rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"open expense":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"open cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"open outlay":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"Open":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.high_price":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"HighPrice"}},"State":"Generated","Terms":[{"high price":{"State":"Generated"}},{"HighPrice":{"Type":"Noun","State":"Generated","Weight":0.99}},{"price":{"State":"Generated","Weight":0.97}},{"high value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"high worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"high fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"high charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"high amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"high bill":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"high rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"high expense":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"high cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"high outlay":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"High":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.low_price":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"LowPrice"}},"State":"Generated","Terms":[{"low price":{"State":"Generated"}},{"LowPrice":{"Type":"Noun","State":"Generated","Weight":0.99}},{"price":{"State":"Generated","Weight":0.97}},{"low value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"low worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"low fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"low charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"low amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"low bill":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"low rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"low expense":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"low cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"low outlay":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"Low":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.candlestick_title":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"Candlestick Title"}},"State":"Generated","Terms":[{"candlestick title":{"State":"Generated"}},{"title":{"State":"Generated","Weight":0.97}},{"candlestick designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"designation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"candlestick name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"candlestick award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"candlestick call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"candlestick heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"candlestick label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"award":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"call":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"heading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"calendar":{"Definition":{"Binding":{"ConceptualEntity":"Calendar"}},"State":"Generated","Terms":[{"calendar":{"State":"Generated"}},{"almanac":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"datebook":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"agenda":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"logbook":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"diary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"schedule":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"timetable":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"calendar.date":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Date"}},"State":"Generated","Terms":[{"date":{"State":"Generated"}},{"moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}],"SemanticType":"Time"},"calendar.year":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Year"}},"State":"Generated","Terms":[{"year":{"State":"Generated"}},{"yr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}],"SemanticType":"Time"},"calendar.quarter":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Quarter"}},"State":"Generated","Terms":[{"quarter":{"State":"Generated"}},{"qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.818}}]},"calendar.month_number":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"MonthNumber"}},"State":"Generated","Terms":[{"month number":{"State":"Generated"}},{"MonthNumber":{"Type":"Noun","State":"Generated","Weight":0.99}},{"month no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"mth number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"calendar.month_name":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"MonthName"}},"State":"Generated","Terms":[{"month name":{"State":"Generated"}},{"MonthName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"month nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"month title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"month label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"month tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"mth name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"calendar.year_month":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"YearMonth"}},"State":"Generated","Terms":[{"year month":{"State":"Generated"}},{"YearMonth":{"Type":"Noun","State":"Generated","Weight":0.99}},{"year mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"yr month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"calendar.day_of_week":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"DayOfWeek"}},"State":"Generated","Terms":[{"day of week":{"State":"Generated"}},{"DayOfWeek":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"days_moving_average_parameter":{"Definition":{"Binding":{"ConceptualEntity":"DaysMovingAverageParameter"}},"State":"Generated","Terms":[{"days moving average parameter":{"State":"Generated"}},{"day moving average parameter":{"Type":"Noun","State":"Generated","Weight":0.78}},{"DaysMovingAverageParameter":{"Type":"Noun","State":"Generated","Weight":0.99}},{"parameter":{"State":"Generated","Weight":0.97}},{"average parameter":{"State":"Generated","Weight":0.97}},{"moving average parameter":{"State":"Generated","Weight":0.97}},{"day moving average stricture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"day moving average limitation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"day moving average restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"day moving average constraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"day moving average consideration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"day moving average boundary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"moving average stricture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"moving average limitation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"moving average restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"moving average constraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}}]},"days_moving_average_parameter.day":{"Definition":{"Binding":{"ConceptualEntity":"DaysMovingAverageParameter","ConceptualProperty":"Days"}},"State":"Generated","Terms":[{"day":{"State":"Generated"}},{"Range moving average (Days)":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.price_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"PriceChange"}},"State":"Generated","Terms":[{"price change":{"State":"Generated"}},{"PriceChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"price alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"price modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"price variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"price transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"price revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"price conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"price adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"price amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"entity__measure.price_change_relative":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"PriceChangeRelative"}},"State":"Generated","Terms":[{"price change relative":{"State":"Generated"}},{"PriceChangeRelative":{"Type":"Noun","State":"Generated","Weight":0.99}},{"relative":{"State":"Generated","Weight":0.97}},{"change relative":{"State":"Generated","Weight":0.97}},{"price change relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"comparative":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"change relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"Change (%)":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"d_ticker.name":{"Definition":{"Binding":{"ConceptualEntity":"dTickers","ConceptualProperty":"Name"}},"State":"Generated","Terms":[{"name":{"State":"Generated"}},{"label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"Company":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}],"NameType":"Name"},"entity__measure.quarterly_pe_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"Pe"}},"State":"Generated","Terms":[{"pe":{"State":"Generated"}},{"PE Ratio":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.quarterly_forward_pe_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"ForwardPe"}},"State":"Generated","Terms":[{"forward pe":{"State":"Generated"}},{"ForwardPe":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"entity__measure.quarterly_peg_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"Peg"}},"State":"Generated","Terms":[{"peg":{"State":"Generated"}},{"fastener":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"hanger":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"pin":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"dowel":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"hook":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"bolt":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"nail":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"spike":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"tack":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"PEG Ratio":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.quarterly_ps_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"Ps"}},"State":"Generated","Terms":[{"ps":{"State":"Generated"}},{"PS Ratio":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.quarterly_market_cap":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"MarketCap"}},"State":"Generated","Terms":[{"market cap":{"State":"Generated"}},{"MarketCap":{"Type":"Noun","State":"Generated","Weight":0.99}},{"cap":{"State":"Generated","Weight":0.97}},{"market lid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"market cover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"market top":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"market stopper":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"market plug":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"lid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"stopper":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"plug":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"market restraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}}]},"entity__measure.quarterly_enterprises_value_revenue_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"EnterprisesValueRevenue"}},"State":"Generated","Terms":[{"enterprises value revenue":{"State":"Generated"}},{"EnterprisesValueRevenue":{"Type":"Noun","State":"Generated","Weight":0.99}},{"revenue":{"State":"Generated","Weight":0.97}},{"value revenue":{"State":"Generated","Weight":0.97}},{"enterprise value income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"value income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"enterprise value profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"enterprise value turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"enterprise value yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"income":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"value profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"value turnover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"value yield":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"profit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"EV/Revenue":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.quarterly_enterprises_value_EBITDA_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"EnterprisesValueEBITDA"}},"State":"Generated","Terms":[{"enterprises value EBITDA":{"State":"Generated"}},{"EnterprisesValueEBITDA":{"Type":"Noun","State":"Generated","Weight":0.99}},{"EBITDA":{"State":"Generated","Weight":0.97}},{"value EBITDA":{"State":"Generated","Weight":0.97}},{"EV/EBITDA":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.quarterly_enterprise_value":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"EnterpriseValue"}},"State":"Generated","Terms":[{"enterprise value":{"State":"Generated"}},{"EnterpriseValue":{"Type":"Noun","State":"Generated","Weight":0.99}},{"value":{"State":"Generated","Weight":0.97}},{"enterprise assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"enterprise worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"enterprise price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"enterprise cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"enterprise charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"enterprise rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"EV":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.quarterly_pb_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"Pb"}},"State":"Generated","Terms":[{"pb":{"State":"Generated"}},{"PB Ratio":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"d_fundamentals_TTM":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"}},"State":"Generated","Terms":[{"d fundamentals TTM":{"State":"Generated"}},{"d fundamental TTM":{"Type":"Noun","State":"Generated","Weight":0.78}},{"dFundamentalsTTM":{"Type":"Noun","State":"Generated","Weight":0.99}},{"TTM":{"State":"Generated","Weight":0.97}},{"fundamentals TTM":{"State":"Generated","Weight":0.97}},{"fundamental TTM":{"Type":"Noun","State":"Generated","Weight":0.7566}}]},"d_fundamentals_TTM.date":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentalsTTM","ConceptualProperty":"Date"}},"State":"Generated","Terms":[{"date":{"State":"Generated"}},{"moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}],"SemanticType":"Time"},"d_fundamentals_TTM.period_type":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentalsTTM","ConceptualProperty":"periodType"}},"State":"Generated","Terms":[{"period type":{"State":"Generated"}},{"periodType":{"Type":"Noun","State":"Generated","Weight":0.99}},{"type":{"State":"Generated","Weight":0.97}},{"period category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"period genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"period manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"period variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"period brand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"period class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"d_fundamentals_TTM.ticker":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentalsTTM","ConceptualProperty":"Ticker"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"ticker":{"State":"Generated"}}]},"d_fundamentals_TTM.trailing_enterprises_value_EBITDA_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentalsTTM","ConceptualProperty":"trailingEnterprisesValueEBITDARatio"}},"State":"Generated","Terms":[{"trailing enterprises value EBITDA ratio":{"State":"Generated"}},{"trailing enterprise value EBITDA ratio":{"Type":"Noun","State":"Generated","Weight":0.78}},{"trailingEnterprisesValueEBITDARatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"EBITDA ratio":{"State":"Generated","Weight":0.97}},{"value EBITDA ratio":{"State":"Generated","Weight":0.97}},{"enterprises value EBITDA ratio":{"State":"Generated","Weight":0.97}},{"enterprise value EBITDA ratio":{"Type":"Noun","State":"Generated","Weight":0.7566}},{"trailing enterprise value ebitda relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing enterprise value ebitda percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing enterprise value ebitda quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing enterprise value ebitda relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"enterprise value ebitda relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"value ebitda relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"value ebitda percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}}]},"d_fundamentals_TTM.trailing_forward_pe_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentalsTTM","ConceptualProperty":"trailingForwardPeRatio"}},"State":"Generated","Terms":[{"trailing forward pe ratio":{"State":"Generated"}},{"trailingForwardPeRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"forward pe ratio":{"State":"Generated","Weight":0.97}},{"trailing forward pe relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing forward pe percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing forward pe quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing forward pe relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"forward pe relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing forward pe proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing forward pe share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"d_fundamentals_TTM.trailing_market_cap":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentalsTTM","ConceptualProperty":"trailingMarketCap"}},"State":"Generated","Terms":[{"trailing market cap":{"State":"Generated"}},{"trailingMarketCap":{"Type":"Noun","State":"Generated","Weight":0.99}},{"cap":{"State":"Generated","Weight":0.97}},{"trailing market lid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing market cover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing market top":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing market stopper":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing market plug":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing market restraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"trailing market restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"trailing market threshold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"lid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"d_fundamentals_TTM.trailing_enterprise_value":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentalsTTM","ConceptualProperty":"trailingEnterpriseValue"}},"State":"Generated","Terms":[{"trailing enterprise value":{"State":"Generated"}},{"trailingEnterpriseValue":{"Type":"Noun","State":"Generated","Weight":0.99}},{"value":{"State":"Generated","Weight":0.97}},{"trailing enterprise assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing enterprise worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing enterprise price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing enterprise cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing enterprise charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing enterprise rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"trailing enterprise importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"trailing enterprise significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"trailing enterprise usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}}]},"d_fundamentals_TTM.trailing_peg_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentalsTTM","ConceptualProperty":"trailingPegRatio"}},"State":"Generated","Terms":[{"trailing peg ratio":{"State":"Generated"}},{"trailingPegRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"trailing peg relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing peg percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing peg quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing peg relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing peg proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing peg share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing peg fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing peg part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"d_fundamentals_TTM.trailing_pe_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentalsTTM","ConceptualProperty":"trailingPeRatio"}},"State":"Generated","Terms":[{"trailing pe ratio":{"State":"Generated"}},{"trailingPeRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"trailing pe relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pe percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pe quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pe relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pe proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing pe share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing pe fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing pe part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"d_fundamentals_TTM.trailing_enterprises_value_revenue_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentalsTTM","ConceptualProperty":"trailingEnterprisesValueRevenueRatio"}},"State":"Generated","Terms":[{"trailing enterprises value revenue ratio":{"State":"Generated"}},{"trailing enterprise value revenue ratio":{"Type":"Noun","State":"Generated","Weight":0.78}},{"trailingEnterprisesValueRevenueRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"revenue ratio":{"State":"Generated","Weight":0.97}},{"value revenue ratio":{"State":"Generated","Weight":0.97}},{"enterprises value revenue ratio":{"State":"Generated","Weight":0.97}},{"enterprise value revenue ratio":{"Type":"Noun","State":"Generated","Weight":0.7566}},{"trailing enterprise value income ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"enterprise value income ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"value income ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"trailing enterprise value profit ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"trailing enterprise value turnover ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"trailing enterprise value yield ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"income ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"enterprise value profit ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"enterprise value turnover ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"enterprise value yield ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}}]},"d_fundamentals_TTM.trailing_pb_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentalsTTM","ConceptualProperty":"trailingPbRatio"}},"State":"Generated","Terms":[{"trailing pb ratio":{"State":"Generated"}},{"trailingPbRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"trailing pb relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pb percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pb quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pb relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pb proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing pb share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing pb fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing pb part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}}]},"d_fundamentals_TTM.trailing_ps_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentalsTTM","ConceptualProperty":"trailingPsRatio"}},"State":"Generated","Terms":[{"trailing ps ratio":{"State":"Generated"}},{"trailingPsRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"trailing ps relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing ps percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing ps quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing ps relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing ps proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing ps share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing ps fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing ps part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"d_fundamentals_3M":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentals3M"}},"State":"Generated","Terms":[{"d fundamentals 3M":{"State":"Generated"}},{"d fundamental 3M":{"Type":"Noun","State":"Generated","Weight":0.78}},{"dFundamentals3M":{"Type":"Noun","State":"Generated","Weight":0.99}},{"3M":{"State":"Generated","Weight":0.97}},{"fundamentals 3M":{"State":"Generated","Weight":0.97}},{"fundamental 3M":{"Type":"Noun","State":"Generated","Weight":0.7566}}]},"d_fundamentals_3M.date":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentals3M","ConceptualProperty":"Date"}},"State":"Generated","Terms":[{"date":{"State":"Generated"}},{"moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}],"SemanticType":"Time"},"d_fundamentals_3M.period_type":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentals3M","ConceptualProperty":"periodType"}},"State":"Generated","Terms":[{"period type":{"State":"Generated"}},{"periodType":{"Type":"Noun","State":"Generated","Weight":0.99}},{"type":{"State":"Generated","Weight":0.97}},{"period category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"period genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"period manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"period variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"period brand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"period class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"d_fundamentals_3M.ticker":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentals3M","ConceptualProperty":"Ticker"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"ticker":{"State":"Generated"}}]},"d_fundamentals_3M.quarterly_pe_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentals3M","ConceptualProperty":"quarterlyPeRatio"}},"State":"Generated","Terms":[{"quarterly pe ratio":{"State":"Generated"}},{"quarterlyPeRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"quarterly pe relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly pe percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly pe quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly pe relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly pe proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly pe share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly pe fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly pe part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"d_fundamentals_3M.quarterly_forward_pe_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentals3M","ConceptualProperty":"quarterlyForwardPeRatio"}},"State":"Generated","Terms":[{"quarterly forward pe ratio":{"State":"Generated"}},{"quarterlyForwardPeRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"forward pe ratio":{"State":"Generated","Weight":0.97}},{"quarterly forward pe relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"quarterly forward pe percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"quarterly forward pe quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"quarterly forward pe relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"forward pe relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly forward pe proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"quarterly forward pe share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"d_fundamentals_3M.quarterly_peg_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentals3M","ConceptualProperty":"quarterlyPegRatio"}},"State":"Generated","Terms":[{"quarterly peg ratio":{"State":"Generated"}},{"quarterlyPegRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"quarterly peg relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly peg percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly peg quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly peg relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly peg proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly peg share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly peg fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly peg part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"d_fundamentals_3M.quarterly_ps_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentals3M","ConceptualProperty":"quarterlyPsRatio"}},"State":"Generated","Terms":[{"quarterly ps ratio":{"State":"Generated"}},{"quarterlyPsRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"quarterly ps relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly ps percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly ps quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly ps relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly ps proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly ps share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly ps fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly ps part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"d_fundamentals_3M.quarterly_market_cap":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentals3M","ConceptualProperty":"quarterlyMarketCap"}},"State":"Generated","Terms":[{"quarterly market cap":{"State":"Generated"}},{"quarterlyMarketCap":{"Type":"Noun","State":"Generated","Weight":0.99}},{"cap":{"State":"Generated","Weight":0.97}},{"quarterly market lid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly market cover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly market top":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly market stopper":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly market plug":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly market restraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"quarterly market restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"quarterly market threshold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"lid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"d_fundamentals_3M.quarterly_enterprises_value_revenue_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentals3M","ConceptualProperty":"quarterlyEnterprisesValueRevenueRatio"}},"State":"Generated","Terms":[{"quarterly enterprises value revenue ratio":{"State":"Generated"}},{"quarterly enterprise value revenue ratio":{"Type":"Noun","State":"Generated","Weight":0.78}},{"quarterlyEnterprisesValueRevenueRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"revenue ratio":{"State":"Generated","Weight":0.97}},{"value revenue ratio":{"State":"Generated","Weight":0.97}},{"enterprises value revenue ratio":{"State":"Generated","Weight":0.97}},{"enterprise value revenue ratio":{"Type":"Noun","State":"Generated","Weight":0.7566}},{"quarterly enterprise value income ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"enterprise value income ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"value income ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"quarterly enterprise value profit ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"quarterly enterprise value turnover ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"quarterly enterprise value yield ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"income ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"enterprise value profit ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"enterprise value turnover ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"enterprise value yield ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}}]},"d_fundamentals_3M.quarterly_enterprises_value_EBITDA_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentals3M","ConceptualProperty":"quarterlyEnterprisesValueEBITDARatio"}},"State":"Generated","Terms":[{"quarterly enterprises value EBITDA ratio":{"State":"Generated"}},{"quarterly enterprise value EBITDA ratio":{"Type":"Noun","State":"Generated","Weight":0.78}},{"quarterlyEnterprisesValueEBITDARatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"EBITDA ratio":{"State":"Generated","Weight":0.97}},{"value EBITDA ratio":{"State":"Generated","Weight":0.97}},{"enterprises value EBITDA ratio":{"State":"Generated","Weight":0.97}},{"enterprise value EBITDA ratio":{"Type":"Noun","State":"Generated","Weight":0.7566}},{"quarterly enterprise value ebitda relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"quarterly enterprise value ebitda percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"quarterly enterprise value ebitda quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"quarterly enterprise value ebitda relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"enterprise value ebitda relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"value ebitda relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"value ebitda percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}}]},"d_fundamentals_3M.quarterly_enterprise_value":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentals3M","ConceptualProperty":"quarterlyEnterpriseValue"}},"State":"Generated","Terms":[{"quarterly enterprise value":{"State":"Generated"}},{"quarterlyEnterpriseValue":{"Type":"Noun","State":"Generated","Weight":0.99}},{"value":{"State":"Generated","Weight":0.97}},{"quarterly enterprise assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly enterprise worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly enterprise price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly enterprise cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly enterprise charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly enterprise rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quarterly enterprise importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"quarterly enterprise significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"quarterly enterprise usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}}]},"d_fundamentals_3M.quarterly_pb_ratio":{"Definition":{"Binding":{"ConceptualEntity":"dFundamentals3M","ConceptualProperty":"quarterlyPbRatio"}},"State":"Generated","Terms":[{"quarterly pb ratio":{"State":"Generated"}},{"quarterlyPbRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"quarterly pb relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly pb percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly pb quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly pb relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"quarterly pb proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly pb share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly pb fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"quarterly pb part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}}]},"entity__measure.quarterly_pe_ratio_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"PePrevious"}},"State":"Generated","Terms":[{"pe previous":{"State":"Generated"}},{"PePrevious":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"entity__measure.quarterly_ps_ratio_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"PsPrevious"}},"State":"Generated","Terms":[{"ps previous":{"State":"Generated"}},{"PsPrevious":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"entity__measure.quarterly_peg_ratio_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"PegPrevious"}},"State":"Generated","Terms":[{"peg previous":{"State":"Generated"}},{"PegPrevious":{"Type":"Noun","State":"Generated","Weight":0.99}},{"fastener previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"hanger previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pin previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"dowel previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"hook previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"bolt previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"nail previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"spike previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"tack previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"entity__measure.quarterly_pb_ratio_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"PbPrevious"}},"State":"Generated","Terms":[{"pb previous":{"State":"Generated"}},{"PbPrevious":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"entity__measure.quarterly_market_cap_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"MarketCapPrevious"}},"State":"Generated","Terms":[{"market cap previous":{"State":"Generated"}},{"MarketCapPrevious":{"Type":"Noun","State":"Generated","Weight":0.99}},{"market lid previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"market cover previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"market top previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"market stopper previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"market plug previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"market restraint previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"market restriction previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"market threshold previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"market limit previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"market control previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}}]},"entity__measure.quarterly_forward_pe_ratio_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"ForwardPePrevious"}},"State":"Generated","Terms":[{"forward pe previous":{"State":"Generated"}},{"ForwardPePrevious":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"entity__measure.quarterly_enterprise_value_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"EnterpriseValuePrevious"}},"State":"Generated","Terms":[{"enterprise value previous":{"State":"Generated"}},{"EnterpriseValuePrevious":{"Type":"Noun","State":"Generated","Weight":0.99}},{"enterprise assessment previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"enterprise worth previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"enterprise price previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"enterprise cost previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"enterprise charge previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"enterprise rate previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"enterprise importance previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"enterprise significance previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"enterprise usefulness previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"enterprise consequence previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}}]},"entity__measure.quarterly_enterprises_value_EBITDA_ratio_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"EnterprisesValueEBITDAPrevious"}},"State":"Generated","Terms":[{"enterprises value EBITDA previous":{"State":"Generated"}},{"EnterprisesValueEBITDAPrevious":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"entity__measure.quarterly_pe_ratio_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"PeChange"}},"State":"Generated","Terms":[{"pe change":{"State":"Generated"}},{"PeChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"pe alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pe modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pe variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pe transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pe revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pe conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pe adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pe amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"entity__measure.ps_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"PsChange"}},"State":"Generated","Terms":[{"ps change":{"State":"Generated"}},{"PsChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"ps alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"ps modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"ps variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"ps transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"ps revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"ps conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"ps adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"ps amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"entity__measure.peg_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"PegChange"}},"State":"Generated","Terms":[{"peg change":{"State":"Generated"}},{"PegChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"peg alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"peg modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"peg variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"peg transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"peg revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"peg conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"peg adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"peg amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"entity__measure.pb_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"PbChange"}},"State":"Generated","Terms":[{"pb change":{"State":"Generated"}},{"PbChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"pb alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pb modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pb variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pb transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pb revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pb conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pb adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pb amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pb difference":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"pb cash":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"entity__measure.enterprises_value_EBITDA_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"EnterprisesValueEBITDAChange"}},"State":"Generated","Terms":[{"enterprises value EBITDA change":{"State":"Generated"}},{"EnterprisesValueEBITDAChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"EBITDA change":{"State":"Generated","Weight":0.97}},{"value EBITDA change":{"State":"Generated","Weight":0.97}},{"enterprise value ebitda alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"value ebitda alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"value ebitda modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}}]},"entity__measure.enterprises_value_revenue_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"EnterprisesValueRevenuePrevious"}},"State":"Generated","Terms":[{"enterprises value revenue previous":{"State":"Generated"}},{"EnterprisesValueRevenuePrevious":{"Type":"Noun","State":"Generated","Weight":0.99}},{"enterprise value income previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.771}},{"enterprise value profit previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}},{"enterprise value turnover previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}},{"enterprise value yield previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}}]},"entity__measure.enterprises_value_revenue_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"EnterprisesValueRevenueChange"}},"State":"Generated","Terms":[{"enterprises value revenue change":{"State":"Generated"}},{"EnterprisesValueRevenueChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"revenue change":{"State":"Generated","Weight":0.97}},{"value revenue change":{"State":"Generated","Weight":0.97}},{"enterprise value income change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"value income change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"income change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"enterprise value profit change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"enterprise value turnover change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"enterprise value yield change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"value profit change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"value turnover change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"value yield change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"profit change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"entity__measure.forward_pe_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"ForwardPeChange"}},"State":"Generated","Terms":[{"forward pe change":{"State":"Generated"}},{"ForwardPeChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"forward pe alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe difference":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"entity__measure.enterprise_value_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"EnterpriseValueChange"}},"State":"Generated","Terms":[{"enterprise value change":{"State":"Generated"}},{"EnterpriseValueChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"value change":{"State":"Generated","Weight":0.97}},{"enterprise value alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"enterprise value modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"enterprise value variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"enterprise value transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"enterprise value revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"enterprise value conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"enterprise value adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"enterprise value amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"value alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"value modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}}]},"entity__measure.market_cap_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"MarketCapChange"}},"State":"Generated","Terms":[{"market cap change":{"State":"Generated"}},{"MarketCapChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"cap change":{"State":"Generated","Weight":0.97}},{"market cap alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"market cap modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"market cap variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"market cap transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"market cap revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"market cap conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"market cap adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"market cap amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"cap alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"cap modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}}]},"entity__measure.trailing_pe_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingPeRatio"}},"State":"Generated","Terms":[{"trailing pe ratio":{"State":"Generated"}},{"trailingPeRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"trailing pe relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pe percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pe quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pe relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pe proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing pe share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing pe fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing pe part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"Trailing PE":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.trailing_pe_ratio_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingPeRatioPrevious"}},"State":"Generated","Terms":[{"trailing pe ratio previous":{"State":"Generated"}},{"trailingPeRatioPrevious":{"Type":"Noun","State":"Generated","Weight":0.99}},{"trailing pe relation previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pe percentage previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pe quotient previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pe relationship previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pe proportion previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing pe share previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing pe fraction previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing pe part previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"entity__measure.trailing_pe_ratio_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingPeRatioChange"}},"State":"Generated","Terms":[{"trailing pe ratio change":{"State":"Generated"}},{"trailingPeRatioChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"ratio change":{"State":"Generated","Weight":0.97}},{"pe ratio change":{"State":"Generated","Weight":0.97}},{"trailing pe ratio alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pe ratio modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pe ratio variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pe ratio transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pe ratio revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pe ratio conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pe ratio adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pe ratio amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"pe ratio alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"pe ratio modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}}]},"entity__measure.trailing_forward_pe_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingForwardPeRatio"}},"State":"Generated","Terms":[{"trailing forward pe ratio":{"State":"Generated"}},{"trailingForwardPeRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"forward pe ratio":{"State":"Generated","Weight":0.97}},{"trailing forward pe relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing forward pe percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing forward pe quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing forward pe relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"forward pe relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"forward pe relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing forward pe proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing forward pe share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"Trailing Foward PE":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.trailing_forward_pe_ratio_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingForwardPeRatioPrevious"}},"State":"Generated","Terms":[{"trailing forward pe ratio previous":{"State":"Generated"}},{"trailingForwardPeRatioPrevious":{"Type":"Noun","State":"Generated","Weight":0.99}},{"trailing forward pe relation previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing forward pe percentage previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing forward pe quotient previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing forward pe relationship previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing forward pe proportion previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"trailing forward pe share previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"trailing forward pe fraction previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}},{"trailing forward pe part previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.504}}]},"entity__measure.trailing_forward_pe_ratio_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingForwardPeRatioChange"}},"State":"Generated","Terms":[{"trailing forward pe ratio change":{"State":"Generated"}},{"trailingForwardPeRatioChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"ratio change":{"State":"Generated","Weight":0.97}},{"pe ratio change":{"State":"Generated","Weight":0.97}},{"forward pe ratio change":{"State":"Generated","Weight":0.97}},{"trailing forward pe ratio alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing forward pe ratio modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing forward pe ratio variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing forward pe ratio transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing forward pe ratio revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing forward pe ratio conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing forward pe ratio adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing forward pe ratio amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"forward pe ratio alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"forward pe ratio modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}}]},"entity__measure.trailing_market_cap":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingMarketCap"}},"State":"Generated","Terms":[{"trailing market cap":{"State":"Generated"}},{"trailingMarketCap":{"Type":"Noun","State":"Generated","Weight":0.99}},{"cap":{"State":"Generated","Weight":0.97}},{"trailing market lid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing market cover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing market top":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing market stopper":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing market plug":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing market restraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"trailing market restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"trailing market threshold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"lid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cover":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"entity__measure.trailing_market_cap_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingMarketCapPrevious"}},"State":"Generated","Terms":[{"trailing market cap previous":{"State":"Generated"}},{"trailingMarketCapPrevious":{"Type":"Noun","State":"Generated","Weight":0.99}},{"trailing market lid previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing market cover previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing market top previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing market stopper previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing market plug previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing market restraint previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"trailing market restriction previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"trailing market threshold previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"trailing market limit previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.474}},{"trailing market control previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.474}}]},"entity__measure.trailing_market_cap_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingMarketCapChange"}},"State":"Generated","Terms":[{"trailing market cap change":{"State":"Generated"}},{"trailingMarketCapChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"cap change":{"State":"Generated","Weight":0.97}},{"trailing market cap alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing market cap modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing market cap variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing market cap transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing market cap revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing market cap conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing market cap adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing market cap amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"cap alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"cap modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}}]},"entity__measure.trailing_enterprise_value":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingEnterpriseValue"}},"State":"Generated","Terms":[{"trailing enterprise value":{"State":"Generated"}},{"trailingEnterpriseValue":{"Type":"Noun","State":"Generated","Weight":0.99}},{"value":{"State":"Generated","Weight":0.97}},{"trailing enterprise assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing enterprise worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing enterprise price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing enterprise cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing enterprise charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing enterprise rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"trailing enterprise importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"trailing enterprise significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"trailing enterprise usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"Trailing EV":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.trailing_enterprise_value_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingEnterpriseValuePrevious"}},"State":"Generated","Terms":[{"trailing enterprise value previous":{"State":"Generated"}},{"trailingEnterpriseValuePrevious":{"Type":"Noun","State":"Generated","Weight":0.99}},{"trailing enterprise assessment previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing enterprise worth previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing enterprise price previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing enterprise cost previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing enterprise charge previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing enterprise rate previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing enterprise importance previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"trailing enterprise significance previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"trailing enterprise usefulness previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"trailing enterprise consequence previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}}]},"entity__measure.trailing_enterprise_value_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingEnterpriseValueChange"}},"State":"Generated","Terms":[{"trailing enterprise value change":{"State":"Generated"}},{"trailingEnterpriseValueChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"value change":{"State":"Generated","Weight":0.97}},{"trailing enterprise value alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing enterprise value modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing enterprise value variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing enterprise value transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing enterprise value revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing enterprise value conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing enterprise value adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing enterprise value amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"value alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"value modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}}]},"entity__measure.trailing_enterprises_value_EBITDA_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingEnterprisesValueEBITDARatio"}},"State":"Generated","Terms":[{"trailing enterprises value EBITDA ratio":{"State":"Generated"}},{"trailingEnterprisesValueEBITDARatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"EBITDA ratio":{"State":"Generated","Weight":0.97}},{"value EBITDA ratio":{"State":"Generated","Weight":0.97}},{"enterprises value EBITDA ratio":{"State":"Generated","Weight":0.97}},{"trailing enterprise value ebitda relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing enterprise value ebitda percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing enterprise value ebitda quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"trailing enterprise value ebitda relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"enterprise value ebitda relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"enterprise value ebitda relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"value ebitda relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"value ebitda percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"Trailing EV/EBITDA":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.trailing_enterprises_value_EBITDA_ratio_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingEnterprisesValueEBITDARatioPrevious"}},"State":"Generated","Terms":[{"trailing enterprises value EBITDA ratio previous":{"State":"Generated"}},{"trailingEnterprisesValueEBITDARatioPrevious":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"entity__measure.trailing_enterprises_value_EBITDA_ratio_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingEnterprisesValueEBITDARatioChange"}},"State":"Generated","Terms":[{"trailing enterprises value EBITDA ratio change":{"State":"Generated"}},{"trailingEnterprisesValueEBITDARatioChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"ratio change":{"State":"Generated","Weight":0.97}},{"EBITDA ratio change":{"State":"Generated","Weight":0.97}},{"value EBITDA ratio change":{"State":"Generated","Weight":0.97}},{"enterprises value EBITDA ratio change":{"State":"Generated","Weight":0.97}},{"enterprise value ebitda ratio alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"enterprise value ebitda ratio modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"enterprise value ebitda ratio variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"enterprise value ebitda ratio transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"enterprise value ebitda ratio revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"enterprise value ebitda ratio conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"enterprise value ebitda ratio adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"enterprise value ebitda ratio amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.52}},{"value ebitda ratio alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"value ebitda ratio modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}}]},"entity__measure.trailing_peg_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingPegRatio"}},"State":"Generated","Terms":[{"trailing peg ratio":{"State":"Generated"}},{"trailingPegRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"trailing peg relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing peg percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing peg quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing peg relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing peg proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing peg share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing peg fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing peg part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"Trailing PEG":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.trailing_peg_ratio_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingPegRatioPrevious"}},"State":"Generated","Terms":[{"trailing peg ratio previous":{"State":"Generated"}},{"trailingPegRatioPrevious":{"Type":"Noun","State":"Generated","Weight":0.99}},{"trailing peg relation previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing peg percentage previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing peg quotient previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing peg relationship previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing peg proportion previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing peg share previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing peg fraction previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing peg part previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"entity__measure.trailing_peg_ratio_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingPegRatioChange"}},"State":"Generated","Terms":[{"trailing peg ratio change":{"State":"Generated"}},{"trailingPegRatioChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"ratio change":{"State":"Generated","Weight":0.97}},{"peg ratio change":{"State":"Generated","Weight":0.97}},{"trailing peg ratio alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing peg ratio modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing peg ratio variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing peg ratio transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing peg ratio revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing peg ratio conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing peg ratio adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing peg ratio amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"peg ratio alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"peg ratio modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}}]},"entity__measure.trailing_enterprises_value_revenue_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingEnterprisesValueRevenueRatio"}},"State":"Generated","Terms":[{"trailing enterprises value revenue ratio":{"State":"Generated"}},{"trailingEnterprisesValueRevenueRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"revenue ratio":{"State":"Generated","Weight":0.97}},{"value revenue ratio":{"State":"Generated","Weight":0.97}},{"enterprises value revenue ratio":{"State":"Generated","Weight":0.97}},{"trailing enterprise value income ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"enterprise value income ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"value income ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"trailing enterprise value profit ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"trailing enterprise value turnover ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"trailing enterprise value yield ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"income ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"enterprise value profit ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"enterprise value turnover ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"enterprise value yield ratio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"Trailing EV/Revenue":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.trailing_enterprises_value_revenue_ratio_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingEnterprisesValueRevenueRatioPrevious"}},"State":"Generated","Terms":[{"trailing enterprises value revenue ratio previous":{"State":"Generated"}},{"trailingEnterprisesValueRevenueRatioPrevious":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"entity__measure.trailing_enterprises_value_revenue_ratio_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingEnterprisesValueRevenueRatioChange"}},"State":"Generated","Terms":[{"trailing enterprises value revenue ratio change":{"State":"Generated"}},{"trailingEnterprisesValueRevenueRatioChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"ratio change":{"State":"Generated","Weight":0.97}},{"revenue ratio change":{"State":"Generated","Weight":0.97}},{"value revenue ratio change":{"State":"Generated","Weight":0.97}},{"enterprises value revenue ratio change":{"State":"Generated","Weight":0.97}},{"enterprise value income ratio change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"value income ratio change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"income ratio change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"enterprise value profit ratio change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"enterprise value turnover ratio change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"enterprise value yield ratio change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}},{"value profit ratio change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"value turnover ratio change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"value yield ratio change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"profit ratio change":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}}]},"entity__measure.trailing_pb_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingPbRatio"}},"State":"Generated","Terms":[{"trailing pb ratio":{"State":"Generated"}},{"trailingPbRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"trailing pb relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pb percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pb quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pb relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing pb proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing pb share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing pb fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing pb part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"Trailing PB":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.trailing_pb_ratio_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingPbRatioPrevious"}},"State":"Generated","Terms":[{"trailing pb ratio previous":{"State":"Generated"}},{"trailingPbRatioPrevious":{"Type":"Noun","State":"Generated","Weight":0.99}},{"trailing pb relation previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pb percentage previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pb quotient previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pb relationship previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pb proportion previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing pb share previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing pb fraction previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing pb part previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"entity__measure.trailing_pb_ratio_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingPbRatioChange"}},"State":"Generated","Terms":[{"trailing pb ratio change":{"State":"Generated"}},{"trailingPbRatioChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"trailing pb ratio alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pb ratio modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pb ratio variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pb ratio transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pb ratio revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pb ratio conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pb ratio adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pb ratio amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing pb ratio difference":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing pb ratio cash":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.474}}]},"entity__measure.trailing_ps_ratio":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingPsRatio"}},"State":"Generated","Terms":[{"trailing ps ratio":{"State":"Generated"}},{"trailingPsRatio":{"Type":"Noun","State":"Generated","Weight":0.99}},{"ratio":{"State":"Generated","Weight":0.97}},{"trailing ps relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing ps percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing ps quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing ps relationship":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"trailing ps proportion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing ps share":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing ps fraction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"trailing ps part":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"relation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quotient":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"Trailing PS":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"entity__measure.trailing_ps_ratio_previous":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingPsRatioPrevious"}},"State":"Generated","Terms":[{"trailing ps ratio previous":{"State":"Generated"}},{"trailingPsRatioPrevious":{"Type":"Noun","State":"Generated","Weight":0.99}},{"trailing ps relation previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing ps percentage previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing ps quotient previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing ps relationship previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing ps proportion previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing ps share previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing ps fraction previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"trailing ps part previous":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"entity__measure.trailing_ps_ratio_change":{"Definition":{"Binding":{"ConceptualEntity":"_Measures","ConceptualProperty":"trailingPsRatioChange"}},"State":"Generated","Terms":[{"trailing ps ratio change":{"State":"Generated"}},{"trailingPsRatioChange":{"Type":"Noun","State":"Generated","Weight":0.99}},{"change":{"State":"Generated","Weight":0.97}},{"ratio change":{"State":"Generated","Weight":0.97}},{"ps ratio change":{"State":"Generated","Weight":0.97}},{"trailing ps ratio alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing ps ratio modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing ps ratio variation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing ps ratio transformation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing ps ratio revolution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing ps ratio conversion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing ps ratio adjustment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"trailing ps ratio amendment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"ps ratio alteration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"ps ratio modification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}}]}},"Relationships":{"d_fundamentals_TTM_has_entity__measure_trailing_ps_ratio_previous":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_ps_ratio_previous":{"Target":{"Entity":"entity__measure.trailing_ps_ratio_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_ps_ratio_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_ps_ratio_previous"}]},"d_fundamentals_TTM_has_entity__measure_trailing_ps_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_ps_ratio":{"Target":{"Entity":"entity__measure.trailing_ps_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_ps_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_ps_ratio"}]},"d_fundamentals_TTM_has_entity__measure_trailing_pb_ratio_change":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_pb_ratio_change":{"Target":{"Entity":"entity__measure.trailing_pb_ratio_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_pb_ratio_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_pb_ratio_change"}]},"d_fundamentals_TTM_has_entity__measure_trailing_pb_ratio_previous":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_pb_ratio_previous":{"Target":{"Entity":"entity__measure.trailing_pb_ratio_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_pb_ratio_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_pb_ratio_previous"}]},"d_fundamentals_TTM_has_entity__measure_trailing_pb_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_pb_ratio":{"Target":{"Entity":"entity__measure.trailing_pb_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_pb_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_pb_ratio"}]},"d_fundamentals_TTM_has_entity__measure_trailing_enterprises_value_revenue_ratio_change":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_enterprises_value_revenue_ratio_change":{"Target":{"Entity":"entity__measure.trailing_enterprises_value_revenue_ratio_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_enterprises_value_revenue_ratio_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_enterprises_value_revenue_ratio_change"}]},"d_fundamentals_TTM_has_entity__measure_trailing_enterprises_value_revenue_ratio_previous":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_enterprises_value_revenue_ratio_previous":{"Target":{"Entity":"entity__measure.trailing_enterprises_value_revenue_ratio_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_enterprises_value_revenue_ratio_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_enterprises_value_revenue_ratio_previous"}]},"d_fundamentals_TTM_has_entity__measure_trailing_enterprises_value_revenue_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_enterprises_value_revenue_ratio":{"Target":{"Entity":"entity__measure.trailing_enterprises_value_revenue_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_enterprises_value_revenue_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_enterprises_value_revenue_ratio"}]},"d_fundamentals_TTM_has_entity__measure_trailing_peg_ratio_change":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_peg_ratio_change":{"Target":{"Entity":"entity__measure.trailing_peg_ratio_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_peg_ratio_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_peg_ratio_change"}]},"d_fundamentals_TTM_has_entity__measure_trailing_peg_ratio_previous":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_peg_ratio_previous":{"Target":{"Entity":"entity__measure.trailing_peg_ratio_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_peg_ratio_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_peg_ratio_previous"}]},"d_fundamentals_TTM_has_entity__measure_trailing_peg_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_peg_ratio":{"Target":{"Entity":"entity__measure.trailing_peg_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_peg_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_peg_ratio"}]},"d_fundamentals_TTM_has_entity__measure_trailing_enterprises_value_EBITDA_ratio_change":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_enterprises_value_EBITDA_ratio_change":{"Target":{"Entity":"entity__measure.trailing_enterprises_value_EBITDA_ratio_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_enterprises_value_EBITDA_ratio_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_enterprises_value_EBITDA_ratio_change"}]},"d_fundamentals_TTM_has_entity__measure_trailing_enterprises_value_EBITDA_ratio_previous":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_enterprises_value_EBITDA_ratio_previous":{"Target":{"Entity":"entity__measure.trailing_enterprises_value_EBITDA_ratio_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_enterprises_value_EBITDA_ratio_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_enterprises_value_EBITDA_ratio_previous"}]},"d_fundamentals_TTM_has_entity__measure_trailing_enterprises_value_EBITDA_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_enterprises_value_EBITDA_ratio":{"Target":{"Entity":"entity__measure.trailing_enterprises_value_EBITDA_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_enterprises_value_EBITDA_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_enterprises_value_EBITDA_ratio"}]},"d_fundamentals_TTM_has_entity__measure_trailing_enterprise_value_change":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_enterprise_value_change":{"Target":{"Entity":"entity__measure.trailing_enterprise_value_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_enterprise_value_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_enterprise_value_change"}]},"d_fundamentals_TTM_has_entity__measure_trailing_enterprise_value_previous":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_enterprise_value_previous":{"Target":{"Entity":"entity__measure.trailing_enterprise_value_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_enterprise_value_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_enterprise_value_previous"}]},"d_fundamentals_TTM_has_entity__measure_trailing_enterprise_value":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_enterprise_value":{"Target":{"Entity":"entity__measure.trailing_enterprise_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_enterprise_value"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_enterprise_value"}]},"d_fundamentals_TTM_has_entity__measure_trailing_market_cap_change":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_market_cap_change":{"Target":{"Entity":"entity__measure.trailing_market_cap_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_market_cap_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_market_cap_change"}]},"d_fundamentals_TTM_has_entity__measure_trailing_market_cap_previous":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_market_cap_previous":{"Target":{"Entity":"entity__measure.trailing_market_cap_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_market_cap_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_market_cap_previous"}]},"d_fundamentals_TTM_has_entity__measure_trailing_market_cap":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_market_cap":{"Target":{"Entity":"entity__measure.trailing_market_cap"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_market_cap"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_market_cap"}]},"d_fundamentals_TTM_has_entity__measure_trailing_forward_pe_ratio_change":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_forward_pe_ratio_change":{"Target":{"Entity":"entity__measure.trailing_forward_pe_ratio_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_forward_pe_ratio_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_forward_pe_ratio_change"}]},"d_fundamentals_TTM_has_entity__measure_trailing_forward_pe_ratio_previous":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_forward_pe_ratio_previous":{"Target":{"Entity":"entity__measure.trailing_forward_pe_ratio_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_forward_pe_ratio_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_forward_pe_ratio_previous"}]},"d_fundamentals_TTM_has_entity__measure_trailing_forward_pe_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_forward_pe_ratio":{"Target":{"Entity":"entity__measure.trailing_forward_pe_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_forward_pe_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_forward_pe_ratio"}]},"d_fundamentals_TTM_has_entity__measure_trailing_pe_ratio_change":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_pe_ratio_change":{"Target":{"Entity":"entity__measure.trailing_pe_ratio_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_pe_ratio_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_pe_ratio_change"}]},"d_fundamentals_TTM_has_entity__measure_trailing_pe_ratio_previous":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_pe_ratio_previous":{"Target":{"Entity":"entity__measure.trailing_pe_ratio_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_pe_ratio_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_pe_ratio_previous"}]},"d_fundamentals_TTM_has_entity__measure_trailing_pe_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_pe_ratio":{"Target":{"Entity":"entity__measure.trailing_pe_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_pe_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_pe_ratio"}]},"d_fundamentals_3M_has_entity__measure_market_cap_change":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.market_cap_change":{"Target":{"Entity":"entity__measure.market_cap_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.market_cap_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_market_cap_change"}]},"d_fundamentals_3M_has_entity__measure_enterprise_value_change":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.enterprise_value_change":{"Target":{"Entity":"entity__measure.enterprise_value_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.enterprise_value_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_enterprise_value_change"}]},"d_fundamentals_3M_has_entity__measure_forward_pe_change":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.forward_pe_change":{"Target":{"Entity":"entity__measure.forward_pe_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.forward_pe_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_forward_pe_change"}]},"d_fundamentals_3M_has_entity__measure_enterprises_value_revenue_change":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.enterprises_value_revenue_change":{"Target":{"Entity":"entity__measure.enterprises_value_revenue_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.enterprises_value_revenue_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_enterprises_value_revenue_change"}]},"d_fundamentals_3M_has_entity__measure_enterprises_value_revenue_previous":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.enterprises_value_revenue_previous":{"Target":{"Entity":"entity__measure.enterprises_value_revenue_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.enterprises_value_revenue_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_enterprises_value_revenue_previous"}]},"d_fundamentals_3M_has_entity__measure_enterprises_value_EBITDA_change":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.enterprises_value_EBITDA_change":{"Target":{"Entity":"entity__measure.enterprises_value_EBITDA_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.enterprises_value_EBITDA_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_enterprises_value_EBITDA_change"}]},"d_fundamentals_3M_has_entity__measure_pb_change":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.pb_change":{"Target":{"Entity":"entity__measure.pb_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.pb_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_pb_change"}]},"d_fundamentals_3M_has_entity__measure_peg_change":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.peg_change":{"Target":{"Entity":"entity__measure.peg_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.peg_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_peg_change"}]},"d_fundamentals_3M_has_entity__measure_ps_change":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.ps_change":{"Target":{"Entity":"entity__measure.ps_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.ps_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_ps_change"}]},"d_fundamentals_3M_has_entity__measure_quarterly_pe_ratio_change":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_pe_ratio_change":{"Target":{"Entity":"entity__measure.quarterly_pe_ratio_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_pe_ratio_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_pe_change"}]},"d_fundamentals_3M_has_entity__measure_quarterly_enterprises_value_EBITDA_ratio_previous":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_enterprises_value_EBITDA_ratio_previous":{"Target":{"Entity":"entity__measure.quarterly_enterprises_value_EBITDA_ratio_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_enterprises_value_EBITDA_ratio_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_enterprises_value_EBITDA_previous"}]},"d_fundamentals_3M_has_entity__measure_quarterly_enterprise_value_previous":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_enterprise_value_previous":{"Target":{"Entity":"entity__measure.quarterly_enterprise_value_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_enterprise_value_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_enterprise_value_previous"}]},"d_fundamentals_3M_has_entity__measure_quarterly_forward_pe_ratio_previous":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_forward_pe_ratio_previous":{"Target":{"Entity":"entity__measure.quarterly_forward_pe_ratio_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_forward_pe_ratio_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_forward_pe_previous"}]},"d_fundamentals_3M_has_entity__measure_quarterly_market_cap_previous":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_market_cap_previous":{"Target":{"Entity":"entity__measure.quarterly_market_cap_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_market_cap_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_market_cap_previous"}]},"d_fundamentals_3M_has_entity__measure_quarterly_pb_ratio_previous":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_pb_ratio_previous":{"Target":{"Entity":"entity__measure.quarterly_pb_ratio_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_pb_ratio_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_pb_previous"}]},"d_fundamentals_3M_has_entity__measure_quarterly_peg_ratio_previous":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_peg_ratio_previous":{"Target":{"Entity":"entity__measure.quarterly_peg_ratio_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_peg_ratio_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_peg_previous"}]},"d_fundamentals_3M_has_entity__measure_quarterly_ps_ratio_previous":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_ps_ratio_previous":{"Target":{"Entity":"entity__measure.quarterly_ps_ratio_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_ps_ratio_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_ps_previous"}]},"d_fundamentals_3M_has_entity__measure_quarterly_pe_ratio_previous":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_pe_ratio_previous":{"Target":{"Entity":"entity__measure.quarterly_pe_ratio_previous"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_pe_ratio_previous"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_pe_previous"}]},"d_fundamentals_3M_has_quarterly_pb_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"d_fundamentals_3M.quarterly_pb_ratio":{"Target":{"Entity":"d_fundamentals_3M.quarterly_pb_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"d_fundamentals_3M.quarterly_pb_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_quarterly_pb_ratios"}]},"d_fundamentals_3M_has_quarterly_enterprise_value":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"d_fundamentals_3M.quarterly_enterprise_value":{"Target":{"Entity":"d_fundamentals_3M.quarterly_enterprise_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"d_fundamentals_3M.quarterly_enterprise_value"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_quarterly_enterprise_values"}]},"d_fundamentals_3M_has_quarterly_enterprises_value_EBITDA_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"d_fundamentals_3M.quarterly_enterprises_value_EBITDA_ratio":{"Target":{"Entity":"d_fundamentals_3M.quarterly_enterprises_value_EBITDA_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"d_fundamentals_3M.quarterly_enterprises_value_EBITDA_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_quarterly_enterprises_value_EBITDA_ratios"}]},"d_fundamentals_3M_has_quarterly_enterprises_value_revenue_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"d_fundamentals_3M.quarterly_enterprises_value_revenue_ratio":{"Target":{"Entity":"d_fundamentals_3M.quarterly_enterprises_value_revenue_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"d_fundamentals_3M.quarterly_enterprises_value_revenue_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_quarterly_enterprises_value_revenue_ratios"}]},"d_fundamentals_3M_has_quarterly_market_cap":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"d_fundamentals_3M.quarterly_market_cap":{"Target":{"Entity":"d_fundamentals_3M.quarterly_market_cap"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"d_fundamentals_3M.quarterly_market_cap"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_quarterly_market_caps"}]},"d_fundamentals_3M_has_quarterly_ps_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"d_fundamentals_3M.quarterly_ps_ratio":{"Target":{"Entity":"d_fundamentals_3M.quarterly_ps_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"d_fundamentals_3M.quarterly_ps_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_quarterly_ps_ratios"}]},"d_fundamentals_3M_has_quarterly_peg_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"d_fundamentals_3M.quarterly_peg_ratio":{"Target":{"Entity":"d_fundamentals_3M.quarterly_peg_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"d_fundamentals_3M.quarterly_peg_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_quarterly_peg_ratios"}]},"d_fundamentals_3M_has_quarterly_forward_pe_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"d_fundamentals_3M.quarterly_forward_pe_ratio":{"Target":{"Entity":"d_fundamentals_3M.quarterly_forward_pe_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"d_fundamentals_3M.quarterly_forward_pe_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_quarterly_forward_pe_ratios"}]},"d_fundamentals_3M_has_quarterly_pe_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"d_fundamentals_3M.quarterly_pe_ratio":{"Target":{"Entity":"d_fundamentals_3M.quarterly_pe_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"d_fundamentals_3M.quarterly_pe_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_quarterly_pe_ratios"}]},"d_fundamentals_3M_has_period_type":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"d_fundamentals_3M.period_type":{"Target":{"Entity":"d_fundamentals_3M.period_type"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"d_fundamentals_3M.period_type"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_period_types"}]},"d_fundamentals_3M_has_date":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"d_fundamentals_3M.date":{"Target":{"Entity":"d_fundamentals_3M.date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"d_fundamentals_3M.date"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_dates"}]},"d_fundamentals_TTM_has_trailing_ps_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"d_fundamentals_TTM.trailing_ps_ratio":{"Target":{"Entity":"d_fundamentals_TTM.trailing_ps_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"d_fundamentals_TTM.trailing_ps_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_ps_ratios"}]},"d_fundamentals_TTM_has_trailing_pb_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"d_fundamentals_TTM.trailing_pb_ratio":{"Target":{"Entity":"d_fundamentals_TTM.trailing_pb_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"d_fundamentals_TTM.trailing_pb_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_pb_ratios"}]},"d_fundamentals_TTM_has_trailing_enterprises_value_revenue_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"d_fundamentals_TTM.trailing_enterprises_value_revenue_ratio":{"Target":{"Entity":"d_fundamentals_TTM.trailing_enterprises_value_revenue_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"d_fundamentals_TTM.trailing_enterprises_value_revenue_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_enterprises_value_revenue_ratios"}]},"d_fundamentals_TTM_has_trailing_pe_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"d_fundamentals_TTM.trailing_pe_ratio":{"Target":{"Entity":"d_fundamentals_TTM.trailing_pe_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"d_fundamentals_TTM.trailing_pe_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_pe_ratios"}]},"d_fundamentals_TTM_has_trailing_peg_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"d_fundamentals_TTM.trailing_peg_ratio":{"Target":{"Entity":"d_fundamentals_TTM.trailing_peg_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"d_fundamentals_TTM.trailing_peg_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_peg_ratios"}]},"d_fundamentals_TTM_has_trailing_enterprise_value":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"d_fundamentals_TTM.trailing_enterprise_value":{"Target":{"Entity":"d_fundamentals_TTM.trailing_enterprise_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"d_fundamentals_TTM.trailing_enterprise_value"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_enterprise_values"}]},"d_fundamentals_TTM_has_trailing_market_cap":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"d_fundamentals_TTM.trailing_market_cap":{"Target":{"Entity":"d_fundamentals_TTM.trailing_market_cap"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"d_fundamentals_TTM.trailing_market_cap"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_market_caps"}]},"d_fundamentals_TTM_has_trailing_forward_pe_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"d_fundamentals_TTM.trailing_forward_pe_ratio":{"Target":{"Entity":"d_fundamentals_TTM.trailing_forward_pe_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"d_fundamentals_TTM.trailing_forward_pe_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_forward_pe_ratios"}]},"d_fundamentals_TTM_has_trailing_enterprises_value_EBITDA_ratio":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"d_fundamentals_TTM.trailing_enterprises_value_EBITDA_ratio":{"Target":{"Entity":"d_fundamentals_TTM.trailing_enterprises_value_EBITDA_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"d_fundamentals_TTM.trailing_enterprises_value_EBITDA_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_enterprises_value_EBITDA_ratios"}]},"d_fundamentals_TTM_has_period_type":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"d_fundamentals_TTM.period_type":{"Target":{"Entity":"d_fundamentals_TTM.period_type"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"d_fundamentals_TTM.period_type"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_period_types"}]},"d_fundamentals_TTM_has_date":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"d_fundamentals_TTM.date":{"Target":{"Entity":"d_fundamentals_TTM.date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"d_fundamentals_TTM.date"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_dates"}]},"d_fundamentals_3M_has_entity__measure_quarterly_pb_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_pb_ratio":{"Target":{"Entity":"entity__measure.quarterly_pb_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_pb_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_pb"}]},"d_fundamentals_3M_has_entity__measure_quarterly_enterprise_value":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_enterprise_value":{"Target":{"Entity":"entity__measure.quarterly_enterprise_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_enterprise_value"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_enterprise_value"}]},"d_fundamentals_3M_has_entity__measure_quarterly_enterprises_value_EBITDA_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_enterprises_value_EBITDA_ratio":{"Target":{"Entity":"entity__measure.quarterly_enterprises_value_EBITDA_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_enterprises_value_EBITDA_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_enterprises_value_EBITDA"}]},"d_fundamentals_3M_has_entity__measure_quarterly_enterprises_value_revenue_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_enterprises_value_revenue_ratio":{"Target":{"Entity":"entity__measure.quarterly_enterprises_value_revenue_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_enterprises_value_revenue_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_enterprises_value_revenue"}]},"d_fundamentals_3M_has_entity__measure_quarterly_market_cap":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_market_cap":{"Target":{"Entity":"entity__measure.quarterly_market_cap"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_market_cap"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_market_cap"}]},"d_fundamentals_3M_has_entity__measure_quarterly_ps_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_ps_ratio":{"Target":{"Entity":"entity__measure.quarterly_ps_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_ps_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_ps"}]},"d_fundamentals_3M_has_entity__measure_quarterly_peg_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_peg_ratio":{"Target":{"Entity":"entity__measure.quarterly_peg_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_peg_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_peg"}]},"d_fundamentals_3M_has_entity__measure_quarterly_forward_pe_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_forward_pe_ratio":{"Target":{"Entity":"entity__measure.quarterly_forward_pe_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_forward_pe_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_forward_pe"}]},"d_fundamentals_3M_has_entity__measure_quarterly_pe_ratio":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"entity__measure.quarterly_pe_ratio":{"Target":{"Entity":"entity__measure.quarterly_pe_ratio"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"entity__measure.quarterly_pe_ratio"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_pe"}]},"d_ticker_has_name":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.name":{"Target":{"Entity":"d_ticker.name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.name"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_names"},{"Name":{"Subject":{"Role":"d_ticker"},"Name":{"Role":"d_ticker.name"}},"State":"Generated","Weight":0.99,"ID":"names_are_names_IDs_of_d_tickers"}]},"fact_indicator_has_entity__measure_price_change_relative":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"entity__measure.price_change_relative":{"Target":{"Entity":"entity__measure.price_change_relative"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"entity__measure.price_change_relative"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_price_change_relative"}]},"fact_indicator_has_entity__measure_price_change":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"entity__measure.price_change":{"Target":{"Entity":"entity__measure.price_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"entity__measure.price_change"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_price_change"}]},"days_moving_average_parameter_has_day":{"Binding":{"ConceptualEntity":"DaysMovingAverageParameter"},"State":"Generated","Roles":{"days_moving_average_parameter":{"Target":{"Entity":"days_moving_average_parameter"}},"days_moving_average_parameter.day":{"Target":{"Entity":"days_moving_average_parameter.day"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"days_moving_average_parameter"},"Object":{"Role":"days_moving_average_parameter.day"}},"State":"Generated","Weight":0.99,"ID":"days_moving_average_parameters_have_days"}]},"calendar_has_day_of_week":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.day_of_week":{"Target":{"Entity":"calendar.day_of_week"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.day_of_week"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_day_of_week"}]},"calendar_has_year_month":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.year_month":{"Target":{"Entity":"calendar.year_month"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.year_month"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_year_months"}]},"calendar_has_month_name":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.month_name":{"Target":{"Entity":"calendar.month_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.month_name"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_month_names"}]},"calendar_has_month_number":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.month_number":{"Target":{"Entity":"calendar.month_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.month_number"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_month_numbers"}]},"calendar_has_quarter":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.quarter":{"Target":{"Entity":"calendar.quarter"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.quarter"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_quarters"}]},"calendar_has_year":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.year":{"Target":{"Entity":"calendar.year"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.year"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_years"}]},"calendar_has_date":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.date":{"Target":{"Entity":"calendar.date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.date"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_dates"}]},"entity__measure_has_candlestick_title":{"Binding":{"ConceptualEntity":"_Measures"},"State":"Generated","Roles":{"entity__measure":{"Target":{"Entity":"entity__measure"}},"entity__measure.candlestick_title":{"Target":{"Entity":"entity__measure.candlestick_title"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"entity__measure"},"Object":{"Role":"entity__measure.candlestick_title"}},"State":"Generated","Weight":0.99,"ID":"Phrasing_measures_have_candlestick_title"}]},"fact_indicator_has_entity__measure_low_price":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"entity__measure.low_price":{"Target":{"Entity":"entity__measure.low_price"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"entity__measure.low_price"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_low_price"},{"Adjective":{"Subject":{"Role":"fact_indicator"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"entity__measure.low_price"}},"State":"Generated","Weight":0.99,"ID":"low_price_indicates_how_expensive_fact_indicators_are"}]},"fact_indicator_has_entity__measure_high_price":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"entity__measure.high_price":{"Target":{"Entity":"entity__measure.high_price"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"entity__measure.high_price"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_high_price"},{"Adjective":{"Subject":{"Role":"fact_indicator"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"entity__measure.high_price"}},"State":"Generated","Weight":0.99,"ID":"high_price_indicates_how_expensive_fact_indicators_are"}]},"fact_indicator_has_entity__measure_open_price":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"entity__measure.open_price":{"Target":{"Entity":"entity__measure.open_price"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"entity__measure.open_price"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_open_price"},{"Adjective":{"Subject":{"Role":"fact_indicator"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"entity__measure.open_price"}},"State":"Generated","Weight":0.99,"ID":"open_price_indicates_how_expensive_fact_indicators_are"}]},"fact_indicator_has_entity__measure_simple_moving_average":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"entity__measure.simple_moving_average":{"Target":{"Entity":"entity__measure.simple_moving_average"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"entity__measure.simple_moving_average"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_SimpleMovingAverage"}]},"fact_indicator_has_entity__measure_total_volume":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"entity__measure.total_volume":{"Target":{"Entity":"entity__measure.total_volume"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"entity__measure.total_volume"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_total_volume"}]},"fact_indicator_has_entity__measure_close_price":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"entity__measure.close_price":{"Target":{"Entity":"entity__measure.close_price"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"entity__measure.close_price"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_close_price"},{"Adjective":{"Subject":{"Role":"fact_indicator"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"entity__measure.close_price"}},"State":"Generated","Weight":0.99,"ID":"close_price_indicates_how_expensive_fact_indicators_are"}]},"fact_indicator_has_time":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"fact_indicator.time":{"Target":{"Entity":"fact_indicator.time"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"fact_indicator.time"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_times"}]},"fact_indicator_has_date":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"fact_indicator.date":{"Target":{"Entity":"fact_indicator.date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"fact_indicator.date"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_dates"}]},"fact_indicator_has_volume":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"fact_indicator.volume":{"Target":{"Entity":"fact_indicator.volume"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"fact_indicator.volume"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_volumes"}]},"fact_indicator_has_close":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"fact_indicator.close":{"Target":{"Entity":"fact_indicator.close"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"fact_indicator.close"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_closes"}]},"fact_indicator_has_low":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"fact_indicator.low":{"Target":{"Entity":"fact_indicator.low"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"fact_indicator.low"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_lows"}]},"fact_indicator_has_high":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"fact_indicator.high":{"Target":{"Entity":"fact_indicator.high"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"fact_indicator.high"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_highs"}]},"fact_indicator_has_open":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"fact_indicator.open":{"Target":{"Entity":"fact_indicator.open"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"fact_indicator.open"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_opens"}]},"fact_indicator_has_DateTime_UTC":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"fact_indicator.DateTime_UTC":{"Target":{"Entity":"fact_indicator.DateTime_UTC"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"fact_indicator.DateTime_UTC"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_DateTime_UTC"}]},"d_ticker_has_valid_range":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.valid_range":{"Target":{"Entity":"d_ticker.valid_range"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.valid_range"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_valid_ranges"}]},"d_ticker_has_range":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.range":{"Target":{"Entity":"d_ticker.range"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.range"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_ranges"}]},"d_ticker_has_data_granularity":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.data_granularity":{"Target":{"Entity":"d_ticker.data_granularity"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.data_granularity"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_data_granularities"}]},"d_ticker_has_current_trading_period":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.current_trading_period":{"Target":{"Entity":"d_ticker.current_trading_period"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.current_trading_period"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_current_trading_periods"}]},"d_ticker_has_price_hint":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.price_hint":{"Target":{"Entity":"d_ticker.price_hint"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.price_hint"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_price_hints"}]},"d_ticker_has_chart_previous_close":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.chart_previous_close":{"Target":{"Entity":"d_ticker.chart_previous_close"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.chart_previous_close"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_chart_previous_closes"}]},"d_ticker_has_short_name":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.short_name":{"Target":{"Entity":"d_ticker.short_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.short_name"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_short_names"}]},"d_ticker_has_long_name":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.long_name":{"Target":{"Entity":"d_ticker.long_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.long_name"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_long_names"}]},"d_ticker_has_regular_market_volume":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.regular_market_volume":{"Target":{"Entity":"d_ticker.regular_market_volume"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.regular_market_volume"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_regular_market_volumes"}]},"d_ticker_has_regular_market_day_low":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.regular_market_day_low":{"Target":{"Entity":"d_ticker.regular_market_day_low"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.regular_market_day_low"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_regular_market_day_lows"}]},"d_ticker_has_regular_market_day_high":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.regular_market_day_high":{"Target":{"Entity":"d_ticker.regular_market_day_high"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.regular_market_day_high"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_regular_market_day_highs"}]},"d_ticker_has_fifty_two_week_low":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.fifty_two_week_low":{"Target":{"Entity":"d_ticker.fifty_two_week_low"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.fifty_two_week_low"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_fifty_two_week_lows"}]},"d_ticker_has_fifty_two_week_high":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.fifty_two_week_high":{"Target":{"Entity":"d_ticker.fifty_two_week_high"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.fifty_two_week_high"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_fifty_two_week_highs"}]},"d_ticker_has_regular_market_price":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.regular_market_price":{"Target":{"Entity":"d_ticker.regular_market_price"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.regular_market_price"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_regular_market_prices"}]},"d_ticker_has_exchange_timezone_name":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.exchange_timezone_name":{"Target":{"Entity":"d_ticker.exchange_timezone_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.exchange_timezone_name"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_exchange_timezone_names"}]},"d_ticker_has_timezone":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.timezone":{"Target":{"Entity":"d_ticker.timezone"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.timezone"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_timezones"}]},"d_ticker_has_gmtoffset":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.gmtoffset":{"Target":{"Entity":"d_ticker.gmtoffset"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.gmtoffset"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_gmtoffsets"}]},"d_ticker_has_has_pre_post_market_data":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.has_pre_post_market_data":{"Target":{"Entity":"d_ticker.has_pre_post_market_data"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.has_pre_post_market_data"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_has_pre_post_market_data"}]},"d_ticker_has_regular_market_time":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.regular_market_time":{"Target":{"Entity":"d_ticker.regular_market_time"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.regular_market_time"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_regular_market_times"}]},"d_ticker_has_first_trade_date":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.first_trade_date":{"Target":{"Entity":"d_ticker.first_trade_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.first_trade_date"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_first_trade_dates"}]},"d_ticker_has_instrument_type":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.instrument_type":{"Target":{"Entity":"d_ticker.instrument_type"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.instrument_type"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_instrument_types"}]},"d_ticker_has_full_exchange_name":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.full_exchange_name":{"Target":{"Entity":"d_ticker.full_exchange_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.full_exchange_name"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_full_exchange_names"}]},"d_ticker_has_exchange_name":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.exchange_name":{"Target":{"Entity":"d_ticker.exchange_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.exchange_name"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_exchange_names"}]},"d_ticker_has_symbol":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.symbol":{"Target":{"Entity":"d_ticker.symbol"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.symbol"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_symbols"}]},"d_ticker_has_currency":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.currency":{"Target":{"Entity":"d_ticker.currency"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.currency"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_currencies"}]},"d_ticker_has_ticker":{"Binding":{"ConceptualEntity":"dTickers"},"State":"Generated","Roles":{"d_ticker":{"Target":{"Entity":"d_ticker"}},"d_ticker.ticker":{"Target":{"Entity":"d_ticker.ticker"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_ticker.ticker"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_tickers"}]},"fact_indicator_indicate":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}}},"Phrasings":[{"Verb":{"Subject":{"Role":"fact_indicator"},"Verbs":[{"indicate":{"State":"Generated"}}]},"State":"Generated","Weight":0.75,"ID":"fact_indicators_indicate"}]},"d_fundamentals_TTM_has_entity__measure_trailing_ps_ratio_change":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"entity__measure.trailing_ps_ratio_change":{"Target":{"Entity":"entity__measure.trailing_ps_ratio_change"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"entity__measure.trailing_ps_ratio_change"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_trailing_ps_ratio_change"}]},"fact_indicator_has_d_ticker":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"d_ticker":{"Target":{"Entity":"d_ticker"},"Nouns":[{"ticker":{"State":"Generated"}}]}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"d_ticker"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_d_tickers"},{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"fact_indicator"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_fact_indicators"}]},"fact_indicator_has_calendar":{"Binding":{"ConceptualEntity":"factIndicators"},"State":"Generated","Roles":{"fact_indicator":{"Target":{"Entity":"fact_indicator"}},"calendar":{"Target":{"Entity":"calendar"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"fact_indicator"},"Object":{"Role":"calendar"}},"State":"Generated","Weight":0.99,"ID":"fact_indicators_have_calendars"},{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"fact_indicator"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_fact_indicators"}]},"d_fundamentals_TTM_has_d_ticker":{"Binding":{"ConceptualEntity":"dFundamentalsTTM"},"State":"Generated","Roles":{"d_fundamentals_TTM":{"Target":{"Entity":"d_fundamentals_TTM"}},"d_ticker":{"Target":{"Entity":"d_ticker"},"Nouns":[{"ticker":{"State":"Generated"}}]}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_TTM"},"Object":{"Role":"d_ticker"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_TTMs_have_d_tickers"},{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_fundamentals_TTM"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_d_fundamentals_TTMs"}]},"d_fundamentals_3M_has_d_ticker":{"Binding":{"ConceptualEntity":"dFundamentals3M"},"State":"Generated","Roles":{"d_fundamentals_3M":{"Target":{"Entity":"d_fundamentals_3M"}},"d_ticker":{"Target":{"Entity":"d_ticker"},"Nouns":[{"ticker":{"State":"Generated"}}]}},"Phrasings":[{"Attribute":{"Subject":{"Role":"d_fundamentals_3M"},"Object":{"Role":"d_ticker"}},"State":"Generated","Weight":0.99,"ID":"d_fundamentals_3M_have_d_tickers"},{"Attribute":{"Subject":{"Role":"d_ticker"},"Object":{"Role":"d_fundamentals_3M"}},"State":"Generated","Weight":0.99,"ID":"d_tickers_have_d_fundamentals_3M"}]}}}
				contentType: json

		expression PathtoTickersCSV = "C:\Users\KlausFolz\Desktop\Repositories\Stock Intelligence\tickers.csv" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]
			lineageTag: bd280823-69d3-4fed-a864-fa0f936fe984
			queryGroup: Parameters

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Text

		expression Interval = "1d" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]
			lineageTag: 29b8c2d7-5179-4c31-af66-f7fc9eae02fd
			queryGroup: Parameters

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Text

		expression Range = "1y" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]
			lineageTag: e5e4eda3-38bf-4b3d-915b-3b5a70d0de55
			queryGroup: Parameters

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Text

		expression dFundamentals = ```
				let
				    //Dynamic timestamps
				    NowLocal = DateTimeZone.LocalNow(),
				    NowDateTime = DateTimeZone.RemoveZone(NowLocal),
				    // Subtract 183 days - 6 months:
				    SixMonthsAgoDateTime = NowDateTime - #duration(183, 0, 0, 0),
				
				    Period1 = Number.ToText(
				        Number.RoundDown(
				            Duration.TotalSeconds(
				                SixMonthsAgoDateTime - #datetime(1970, 1, 1, 0, 0, 0)
				            )
				        )
				    ),
				    Period2 = Number.ToText(
				        Number.RoundDown(
				            Duration.TotalSeconds(
				                NowDateTime - #datetime(1970, 1, 1, 0, 0, 0)
				            )
				        )
				    ),
				
				    //Import the CSV of Tickers
				    Source = Csv.Document(
				        File.Contents(PathtoTickersCSV),
				        [Delimiter=",", Columns=1, QuoteStyle=QuoteStyle.None]
				    ),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Ticker", type text}}),
				
				    //fundamentals-timeseries API call for each Ticker
				    WithAPICall = Table.AddColumn(
				        #"Changed Type",
				        "APICall",
				        each
				            Web.Contents(
				                "https://query1.finance.yahoo.com",
				                [
				                    RelativePath = "ws/fundamentals-timeseries/v1/finance/timeseries/" & [Ticker],
				                    Query = [
				                        merge                  = "false",
				                        padTimeSeries         = "true",
				                        period1               = Period1,
				                        period2               = Period2,
				                        type                  = 
				                            "quarterlyMarketCap,trailingMarketCap," &
				                            "quarterlyEnterpriseValue,trailingEnterpriseValue," &
				                            "quarterlyPeRatio,trailingPeRatio," &
				                            "quarterlyForwardPeRatio,trailingForwardPeRatio," &
				                            "quarterlyPegRatio,trailingPegRatio," &
				                            "quarterlyPsRatio,trailingPsRatio," &
				                            "quarterlyPbRatio,trailingPbRatio," &
				                            "quarterlyEnterprisesValueRevenueRatio,trailingEnterprisesValueRevenueRatio," &
				                            "quarterlyEnterprisesValueEBITDARatio,trailingEnterprisesValueEBITDARatio",
				                        lang                  = "en-US",
				                        region                = "US"
				                    ]
				                ]
				            )
				    ),
				    WithParsedJSON = Table.AddColumn(
				        WithAPICall,
				        "ParsedJSON",
				        each Json.Document([APICall])
				    ),
				    //Transform the 'timeseries' data into a normalized table.
				    WithDataTable = Table.AddColumn(
				        WithParsedJSON,
				        "MetricsData",
				        each
				            let
				                rawJson   = [ParsedJSON],
				                timeSeriesRecord = rawJson[timeseries]?,
				                resultsList = timeSeriesRecord[result]?,
				
				                // Combine all metrics into a single list of records:
				                combinedRecords =
				                    if resultsList = null 
				                    then 
				                        {}
				                    else 
				                        List.Combine(
				                            List.Transform(
				                                resultsList,
				                                (metric) =>
				                                    let
				                                        // examples "trailingPeRatio", "quarterlyMarketCap"
				                                        metricType = metric[meta][type]{0},
				
				                                        // Timestamps list
				                                        tsList = metric[timestamp]?,
				
				                                        // Each metric's data array is stored under the same name as 'metricType'
				                                        // For example: metric["trailingPeRatio"] or metric["quarterlyMarketCap"]...
				                                        metricArray = Record.FieldOrDefault(metric, metricType, null)
				                                    in
				                                        if (tsList <> null and metricArray <> null) then
				                                            List.Transform(
				                                                List.Zip({tsList, metricArray}),
				                                                (pair) =>
				                                                    [
				                                                        timestamp       = pair{0},
				                                                        metricType      = metricType,
				                                                        asOfDate        = pair{1}[asOfDate]?,
				                                                        periodType      = pair{1}[periodType]?,
				                                                        rawValue        = pair{1}[reportedValue]?[raw]?,
				                                                        formattedValue  = pair{1}[reportedValue]?[fmt]?
				                                                    ]
				                                            )
				                                        else
				                                            {}
				                            )
				                        ),
				
				                // Convert list of records into a Table
				                dataTable = Table.FromRecords(combinedRecords)
				            in
				                dataTable
				    ),
				    ExpandedData = Table.ExpandTableColumn(
				        WithDataTable,
				        "MetricsData",
				        {"timestamp", "metricType", "asOfDate", "periodType", "rawValue", "formattedValue"},
				        {"timestamp", "metricType", "asOfDate", "periodType", "rawValue", "formattedValue"}
				    ),
				    //Convert 'timestamp' to a human-readable DateTime
				    WithDateTime = Table.TransformColumns(
				        ExpandedData,
				        {
				            {
				                "timestamp",
				                each #datetime(1970, 1, 1, 0, 0, 0) + #duration(0,0,0,_),
				                type datetime
				            }
				        }
				    ),
				    RenamedCols = Table.RenameColumns(
				        WithDateTime,
				        {
				            {"timestamp", "DateTime (UTC)"},
				            {"rawValue", "Raw Value"},
				            {"formattedValue", "Formatted Value"}
				        }
				    ),
				    //Remove JSON columns 
				    RemovedApiColumns = Table.RemoveColumns(RenamedCols, {"APICall", "ParsedJSON"}),
				    
				    ChangedTypes = Table.TransformColumnTypes(
				        RemovedApiColumns,
				        {
				            {"Raw Value", type number}
				        }
				    ),
				    #"Inserted Date" = Table.AddColumn(ChangedTypes, "Date", each DateTime.Date([#"DateTime (UTC)"]), type date),
				    #"Removed Other Columns" = Table.SelectColumns(#"Inserted Date",{"Date", "Raw Value", "periodType", "metricType", "Ticker"})
				in
				    #"Removed Other Columns"
				```
			lineageTag: 75a3d5a5-4f48-4630-af7b-f38116606ca0
			queryGroup: 'Dimension Tables'

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		queryGroup Parameters

			annotation PBI_QueryGroupOrder = 0

		queryGroup 'Fact Tables'

			annotation PBI_QueryGroupOrder = 1

		queryGroup 'Dimension Tables'

			annotation PBI_QueryGroupOrder = 2

		annotation __PBI_TimeIntelligenceEnabled = 0

		annotation PBIDesktopVersion = 2.140.1577.0 (25.02)+00af0910c5ca19a229c472b0dfc17a2c488f6b0a

		annotation PBI_QueryOrder = ["factIndicators","PathtoTickersCSV","Interval","Range","dTickers","_Measures","dFundamentals","dFundamentalsTTM","dFundamentals3M"]

		annotation PBI_ProTooling = ["DevMode","TMDLView_Desktop","CalcGroup"]

